package com.svw.usp.model.standard;

import java.io.Serializable;
import java.math.BigDecimal;

public class TuCostsLadderKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_costs_ladder.SMS_COSTS
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private Integer smsCosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_costs_ladder.SMS_LADDER
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private BigDecimal smsLadder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_costs_ladder.SMS_COSTS
     *
     * @return the value of tu_costs_ladder.SMS_COSTS
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Integer getSmsCosts() {
        return smsCosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_costs_ladder.SMS_COSTS
     *
     * @param smsCosts the value for tu_costs_ladder.SMS_COSTS
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setSmsCosts(Integer smsCosts) {
        this.smsCosts = smsCosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_costs_ladder.SMS_LADDER
     *
     * @return the value of tu_costs_ladder.SMS_LADDER
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public BigDecimal getSmsLadder() {
        return smsLadder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_costs_ladder.SMS_LADDER
     *
     * @param smsLadder the value for tu_costs_ladder.SMS_LADDER
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setSmsLadder(BigDecimal smsLadder) {
        this.smsLadder = smsLadder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TuCostsLadderKey other = (TuCostsLadderKey) that;
        return (this.getSmsCosts() == null ? other.getSmsCosts() == null : this.getSmsCosts().equals(other.getSmsCosts()))
            && (this.getSmsLadder() == null ? other.getSmsLadder() == null : this.getSmsLadder().equals(other.getSmsLadder()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSmsCosts() == null) ? 0 : getSmsCosts().hashCode());
        result = prime * result + ((getSmsLadder() == null) ? 0 : getSmsLadder().hashCode());
        return result;
    }
}