package com.svw.usp.model.standard;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TuSmsChannelCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public TuSmsChannelCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChannelCodeIsNull() {
            addCriterion("CHANNEL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNotNull() {
            addCriterion("CHANNEL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeEqualTo(String value) {
            addCriterion("CHANNEL_CODE =", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotEqualTo(String value) {
            addCriterion("CHANNEL_CODE <>", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThan(String value) {
            addCriterion("CHANNEL_CODE >", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_CODE >=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThan(String value) {
            addCriterion("CHANNEL_CODE <", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_CODE <=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLike(String value) {
            addCriterion("CHANNEL_CODE like", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotLike(String value) {
            addCriterion("CHANNEL_CODE not like", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIn(List<String> values) {
            addCriterion("CHANNEL_CODE in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotIn(List<String> values) {
            addCriterion("CHANNEL_CODE not in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeBetween(String value1, String value2) {
            addCriterion("CHANNEL_CODE between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_CODE not between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNull() {
            addCriterion("CHANNEL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andChannelNameIsNotNull() {
            addCriterion("CHANNEL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andChannelNameEqualTo(String value) {
            addCriterion("CHANNEL_NAME =", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotEqualTo(String value) {
            addCriterion("CHANNEL_NAME <>", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThan(String value) {
            addCriterion("CHANNEL_NAME >", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_NAME >=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThan(String value) {
            addCriterion("CHANNEL_NAME <", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_NAME <=", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameLike(String value) {
            addCriterion("CHANNEL_NAME like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotLike(String value) {
            addCriterion("CHANNEL_NAME not like", value, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameIn(List<String> values) {
            addCriterion("CHANNEL_NAME in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotIn(List<String> values) {
            addCriterion("CHANNEL_NAME not in", values, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameBetween(String value1, String value2) {
            addCriterion("CHANNEL_NAME between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelNameNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_NAME not between", value1, value2, "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelHostIsNull() {
            addCriterion("CHANNEL_HOST is null");
            return (Criteria) this;
        }

        public Criteria andChannelHostIsNotNull() {
            addCriterion("CHANNEL_HOST is not null");
            return (Criteria) this;
        }

        public Criteria andChannelHostEqualTo(String value) {
            addCriterion("CHANNEL_HOST =", value, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostNotEqualTo(String value) {
            addCriterion("CHANNEL_HOST <>", value, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostGreaterThan(String value) {
            addCriterion("CHANNEL_HOST >", value, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_HOST >=", value, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostLessThan(String value) {
            addCriterion("CHANNEL_HOST <", value, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_HOST <=", value, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostLike(String value) {
            addCriterion("CHANNEL_HOST like", value, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostNotLike(String value) {
            addCriterion("CHANNEL_HOST not like", value, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostIn(List<String> values) {
            addCriterion("CHANNEL_HOST in", values, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostNotIn(List<String> values) {
            addCriterion("CHANNEL_HOST not in", values, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostBetween(String value1, String value2) {
            addCriterion("CHANNEL_HOST between", value1, value2, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelHostNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_HOST not between", value1, value2, "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameIsNull() {
            addCriterion("CHANNEL_USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameIsNotNull() {
            addCriterion("CHANNEL_USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameEqualTo(String value) {
            addCriterion("CHANNEL_USER_NAME =", value, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameNotEqualTo(String value) {
            addCriterion("CHANNEL_USER_NAME <>", value, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameGreaterThan(String value) {
            addCriterion("CHANNEL_USER_NAME >", value, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_USER_NAME >=", value, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameLessThan(String value) {
            addCriterion("CHANNEL_USER_NAME <", value, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_USER_NAME <=", value, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameLike(String value) {
            addCriterion("CHANNEL_USER_NAME like", value, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameNotLike(String value) {
            addCriterion("CHANNEL_USER_NAME not like", value, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameIn(List<String> values) {
            addCriterion("CHANNEL_USER_NAME in", values, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameNotIn(List<String> values) {
            addCriterion("CHANNEL_USER_NAME not in", values, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameBetween(String value1, String value2) {
            addCriterion("CHANNEL_USER_NAME between", value1, value2, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_USER_NAME not between", value1, value2, "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordIsNull() {
            addCriterion("CHANNEL_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordIsNotNull() {
            addCriterion("CHANNEL_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordEqualTo(String value) {
            addCriterion("CHANNEL_PASSWORD =", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordNotEqualTo(String value) {
            addCriterion("CHANNEL_PASSWORD <>", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordGreaterThan(String value) {
            addCriterion("CHANNEL_PASSWORD >", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_PASSWORD >=", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordLessThan(String value) {
            addCriterion("CHANNEL_PASSWORD <", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_PASSWORD <=", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordLike(String value) {
            addCriterion("CHANNEL_PASSWORD like", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordNotLike(String value) {
            addCriterion("CHANNEL_PASSWORD not like", value, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordIn(List<String> values) {
            addCriterion("CHANNEL_PASSWORD in", values, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordNotIn(List<String> values) {
            addCriterion("CHANNEL_PASSWORD not in", values, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordBetween(String value1, String value2) {
            addCriterion("CHANNEL_PASSWORD between", value1, value2, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_PASSWORD not between", value1, value2, "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyIsNull() {
            addCriterion("CHANNEL_SECRET_KEY is null");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyIsNotNull() {
            addCriterion("CHANNEL_SECRET_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyEqualTo(String value) {
            addCriterion("CHANNEL_SECRET_KEY =", value, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyNotEqualTo(String value) {
            addCriterion("CHANNEL_SECRET_KEY <>", value, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyGreaterThan(String value) {
            addCriterion("CHANNEL_SECRET_KEY >", value, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_SECRET_KEY >=", value, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyLessThan(String value) {
            addCriterion("CHANNEL_SECRET_KEY <", value, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_SECRET_KEY <=", value, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyLike(String value) {
            addCriterion("CHANNEL_SECRET_KEY like", value, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyNotLike(String value) {
            addCriterion("CHANNEL_SECRET_KEY not like", value, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyIn(List<String> values) {
            addCriterion("CHANNEL_SECRET_KEY in", values, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyNotIn(List<String> values) {
            addCriterion("CHANNEL_SECRET_KEY not in", values, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyBetween(String value1, String value2) {
            addCriterion("CHANNEL_SECRET_KEY between", value1, value2, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_SECRET_KEY not between", value1, value2, "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andChannelPriceIsNull() {
            addCriterion("CHANNEL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andChannelPriceIsNotNull() {
            addCriterion("CHANNEL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andChannelPriceEqualTo(BigDecimal value) {
            addCriterion("CHANNEL_PRICE =", value, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceNotEqualTo(BigDecimal value) {
            addCriterion("CHANNEL_PRICE <>", value, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceGreaterThan(BigDecimal value) {
            addCriterion("CHANNEL_PRICE >", value, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CHANNEL_PRICE >=", value, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceLessThan(BigDecimal value) {
            addCriterion("CHANNEL_PRICE <", value, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CHANNEL_PRICE <=", value, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceIn(List<BigDecimal> values) {
            addCriterion("CHANNEL_PRICE in", values, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceNotIn(List<BigDecimal> values) {
            addCriterion("CHANNEL_PRICE not in", values, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHANNEL_PRICE between", value1, value2, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andChannelPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CHANNEL_PRICE not between", value1, value2, "channelPrice");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_CODE) like", value.toUpperCase(), "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelNameLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_NAME) like", value.toUpperCase(), "channelName");
            return (Criteria) this;
        }

        public Criteria andChannelHostLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_HOST) like", value.toUpperCase(), "channelHost");
            return (Criteria) this;
        }

        public Criteria andChannelUserNameLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_USER_NAME) like", value.toUpperCase(), "channelUserName");
            return (Criteria) this;
        }

        public Criteria andChannelPasswordLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_PASSWORD) like", value.toUpperCase(), "channelPassword");
            return (Criteria) this;
        }

        public Criteria andChannelSecretKeyLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_SECRET_KEY) like", value.toUpperCase(), "channelSecretKey");
            return (Criteria) this;
        }

        public Criteria andCreateByLikeInsensitive(String value) {
            addCriterion("upper(CREATE_BY) like", value.toUpperCase(), "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLikeInsensitive(String value) {
            addCriterion("upper(UPDATE_BY) like", value.toUpperCase(), "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_channel
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}