package com.svw.usp.model.standard;

import java.io.Serializable;
import java.util.Date;

public class TuSmsReceive implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_receive.SMS_MSG_ID
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String smsMsgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_receive.SMS_CHANNEL_CODE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String smsChannelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_receive.SMS_CHANNEL_USERNAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String smsChannelUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_receive.SMS_CHANNEL_PASSWORD
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String smsChannelPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_receive.SMS_MOBILE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String smsMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_receive.SMS_CONTENT
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String smsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_receive.SMS_RECEIVE_TIME_YYS
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private Date smsReceiveTimeYys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_receive.SMS_RECEIVE_TIME_PT
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private Date smsReceiveTimePt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_receive
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_receive.SMS_MSG_ID
     *
     * @return the value of tu_sms_receive.SMS_MSG_ID
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getSmsMsgId() {
        return smsMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_receive.SMS_MSG_ID
     *
     * @param smsMsgId the value for tu_sms_receive.SMS_MSG_ID
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setSmsMsgId(String smsMsgId) {
        this.smsMsgId = smsMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_receive.SMS_CHANNEL_CODE
     *
     * @return the value of tu_sms_receive.SMS_CHANNEL_CODE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getSmsChannelCode() {
        return smsChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_receive.SMS_CHANNEL_CODE
     *
     * @param smsChannelCode the value for tu_sms_receive.SMS_CHANNEL_CODE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setSmsChannelCode(String smsChannelCode) {
        this.smsChannelCode = smsChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_receive.SMS_CHANNEL_USERNAME
     *
     * @return the value of tu_sms_receive.SMS_CHANNEL_USERNAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getSmsChannelUsername() {
        return smsChannelUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_receive.SMS_CHANNEL_USERNAME
     *
     * @param smsChannelUsername the value for tu_sms_receive.SMS_CHANNEL_USERNAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setSmsChannelUsername(String smsChannelUsername) {
        this.smsChannelUsername = smsChannelUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_receive.SMS_CHANNEL_PASSWORD
     *
     * @return the value of tu_sms_receive.SMS_CHANNEL_PASSWORD
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getSmsChannelPassword() {
        return smsChannelPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_receive.SMS_CHANNEL_PASSWORD
     *
     * @param smsChannelPassword the value for tu_sms_receive.SMS_CHANNEL_PASSWORD
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setSmsChannelPassword(String smsChannelPassword) {
        this.smsChannelPassword = smsChannelPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_receive.SMS_MOBILE
     *
     * @return the value of tu_sms_receive.SMS_MOBILE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getSmsMobile() {
        return smsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_receive.SMS_MOBILE
     *
     * @param smsMobile the value for tu_sms_receive.SMS_MOBILE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setSmsMobile(String smsMobile) {
        this.smsMobile = smsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_receive.SMS_CONTENT
     *
     * @return the value of tu_sms_receive.SMS_CONTENT
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getSmsContent() {
        return smsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_receive.SMS_CONTENT
     *
     * @param smsContent the value for tu_sms_receive.SMS_CONTENT
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setSmsContent(String smsContent) {
        this.smsContent = smsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_receive.SMS_RECEIVE_TIME_YYS
     *
     * @return the value of tu_sms_receive.SMS_RECEIVE_TIME_YYS
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Date getSmsReceiveTimeYys() {
        return smsReceiveTimeYys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_receive.SMS_RECEIVE_TIME_YYS
     *
     * @param smsReceiveTimeYys the value for tu_sms_receive.SMS_RECEIVE_TIME_YYS
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setSmsReceiveTimeYys(Date smsReceiveTimeYys) {
        this.smsReceiveTimeYys = smsReceiveTimeYys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_receive.SMS_RECEIVE_TIME_PT
     *
     * @return the value of tu_sms_receive.SMS_RECEIVE_TIME_PT
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Date getSmsReceiveTimePt() {
        return smsReceiveTimePt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_receive.SMS_RECEIVE_TIME_PT
     *
     * @param smsReceiveTimePt the value for tu_sms_receive.SMS_RECEIVE_TIME_PT
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setSmsReceiveTimePt(Date smsReceiveTimePt) {
        this.smsReceiveTimePt = smsReceiveTimePt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TuSmsReceive other = (TuSmsReceive) that;
        return (this.getSmsMsgId() == null ? other.getSmsMsgId() == null : this.getSmsMsgId().equals(other.getSmsMsgId()))
            && (this.getSmsChannelCode() == null ? other.getSmsChannelCode() == null : this.getSmsChannelCode().equals(other.getSmsChannelCode()))
            && (this.getSmsChannelUsername() == null ? other.getSmsChannelUsername() == null : this.getSmsChannelUsername().equals(other.getSmsChannelUsername()))
            && (this.getSmsChannelPassword() == null ? other.getSmsChannelPassword() == null : this.getSmsChannelPassword().equals(other.getSmsChannelPassword()))
            && (this.getSmsMobile() == null ? other.getSmsMobile() == null : this.getSmsMobile().equals(other.getSmsMobile()))
            && (this.getSmsContent() == null ? other.getSmsContent() == null : this.getSmsContent().equals(other.getSmsContent()))
            && (this.getSmsReceiveTimeYys() == null ? other.getSmsReceiveTimeYys() == null : this.getSmsReceiveTimeYys().equals(other.getSmsReceiveTimeYys()))
            && (this.getSmsReceiveTimePt() == null ? other.getSmsReceiveTimePt() == null : this.getSmsReceiveTimePt().equals(other.getSmsReceiveTimePt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSmsMsgId() == null) ? 0 : getSmsMsgId().hashCode());
        result = prime * result + ((getSmsChannelCode() == null) ? 0 : getSmsChannelCode().hashCode());
        result = prime * result + ((getSmsChannelUsername() == null) ? 0 : getSmsChannelUsername().hashCode());
        result = prime * result + ((getSmsChannelPassword() == null) ? 0 : getSmsChannelPassword().hashCode());
        result = prime * result + ((getSmsMobile() == null) ? 0 : getSmsMobile().hashCode());
        result = prime * result + ((getSmsContent() == null) ? 0 : getSmsContent().hashCode());
        result = prime * result + ((getSmsReceiveTimeYys() == null) ? 0 : getSmsReceiveTimeYys().hashCode());
        result = prime * result + ((getSmsReceiveTimePt() == null) ? 0 : getSmsReceiveTimePt().hashCode());
        return result;
    }
}