package com.svw.usp.model.standard;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TuSmsArchiveCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public TuSmsArchiveCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSmsMsgIdIsNull() {
            addCriterion("SMS_MSG_ID is null");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdIsNotNull() {
            addCriterion("SMS_MSG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdEqualTo(String value) {
            addCriterion("SMS_MSG_ID =", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdNotEqualTo(String value) {
            addCriterion("SMS_MSG_ID <>", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdGreaterThan(String value) {
            addCriterion("SMS_MSG_ID >", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_MSG_ID >=", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdLessThan(String value) {
            addCriterion("SMS_MSG_ID <", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdLessThanOrEqualTo(String value) {
            addCriterion("SMS_MSG_ID <=", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdLike(String value) {
            addCriterion("SMS_MSG_ID like", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdNotLike(String value) {
            addCriterion("SMS_MSG_ID not like", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdIn(List<String> values) {
            addCriterion("SMS_MSG_ID in", values, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdNotIn(List<String> values) {
            addCriterion("SMS_MSG_ID not in", values, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdBetween(String value1, String value2) {
            addCriterion("SMS_MSG_ID between", value1, value2, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdNotBetween(String value1, String value2) {
            addCriterion("SMS_MSG_ID not between", value1, value2, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListIsNull() {
            addCriterion("SMS_MOBILE_LIST is null");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListIsNotNull() {
            addCriterion("SMS_MOBILE_LIST is not null");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListEqualTo(String value) {
            addCriterion("SMS_MOBILE_LIST =", value, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListNotEqualTo(String value) {
            addCriterion("SMS_MOBILE_LIST <>", value, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListGreaterThan(String value) {
            addCriterion("SMS_MOBILE_LIST >", value, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_MOBILE_LIST >=", value, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListLessThan(String value) {
            addCriterion("SMS_MOBILE_LIST <", value, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListLessThanOrEqualTo(String value) {
            addCriterion("SMS_MOBILE_LIST <=", value, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListLike(String value) {
            addCriterion("SMS_MOBILE_LIST like", value, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListNotLike(String value) {
            addCriterion("SMS_MOBILE_LIST not like", value, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListIn(List<String> values) {
            addCriterion("SMS_MOBILE_LIST in", values, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListNotIn(List<String> values) {
            addCriterion("SMS_MOBILE_LIST not in", values, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListBetween(String value1, String value2) {
            addCriterion("SMS_MOBILE_LIST between", value1, value2, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListNotBetween(String value1, String value2) {
            addCriterion("SMS_MOBILE_LIST not between", value1, value2, "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsContentIsNull() {
            addCriterion("SMS_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andSmsContentIsNotNull() {
            addCriterion("SMS_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsContentEqualTo(String value) {
            addCriterion("SMS_CONTENT =", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotEqualTo(String value) {
            addCriterion("SMS_CONTENT <>", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentGreaterThan(String value) {
            addCriterion("SMS_CONTENT >", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CONTENT >=", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLessThan(String value) {
            addCriterion("SMS_CONTENT <", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLessThanOrEqualTo(String value) {
            addCriterion("SMS_CONTENT <=", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLike(String value) {
            addCriterion("SMS_CONTENT like", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotLike(String value) {
            addCriterion("SMS_CONTENT not like", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentIn(List<String> values) {
            addCriterion("SMS_CONTENT in", values, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotIn(List<String> values) {
            addCriterion("SMS_CONTENT not in", values, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentBetween(String value1, String value2) {
            addCriterion("SMS_CONTENT between", value1, value2, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotBetween(String value1, String value2) {
            addCriterion("SMS_CONTENT not between", value1, value2, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsSendManIsNull() {
            addCriterion("SMS_SEND_MAN is null");
            return (Criteria) this;
        }

        public Criteria andSmsSendManIsNotNull() {
            addCriterion("SMS_SEND_MAN is not null");
            return (Criteria) this;
        }

        public Criteria andSmsSendManEqualTo(String value) {
            addCriterion("SMS_SEND_MAN =", value, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManNotEqualTo(String value) {
            addCriterion("SMS_SEND_MAN <>", value, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManGreaterThan(String value) {
            addCriterion("SMS_SEND_MAN >", value, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_SEND_MAN >=", value, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManLessThan(String value) {
            addCriterion("SMS_SEND_MAN <", value, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManLessThanOrEqualTo(String value) {
            addCriterion("SMS_SEND_MAN <=", value, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManLike(String value) {
            addCriterion("SMS_SEND_MAN like", value, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManNotLike(String value) {
            addCriterion("SMS_SEND_MAN not like", value, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManIn(List<String> values) {
            addCriterion("SMS_SEND_MAN in", values, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManNotIn(List<String> values) {
            addCriterion("SMS_SEND_MAN not in", values, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManBetween(String value1, String value2) {
            addCriterion("SMS_SEND_MAN between", value1, value2, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsSendManNotBetween(String value1, String value2) {
            addCriterion("SMS_SEND_MAN not between", value1, value2, "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeIsNull() {
            addCriterion("SMS_RECEIVE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeIsNotNull() {
            addCriterion("SMS_RECEIVE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME =", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeNotEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME <>", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeGreaterThan(Date value) {
            addCriterion("SMS_RECEIVE_TIME >", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME >=", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeLessThan(Date value) {
            addCriterion("SMS_RECEIVE_TIME <", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME <=", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeIn(List<Date> values) {
            addCriterion("SMS_RECEIVE_TIME in", values, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeNotIn(List<Date> values) {
            addCriterion("SMS_RECEIVE_TIME not in", values, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeBetween(Date value1, Date value2) {
            addCriterion("SMS_RECEIVE_TIME between", value1, value2, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("SMS_RECEIVE_TIME not between", value1, value2, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsStatusIsNull() {
            addCriterion("SMS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSmsStatusIsNotNull() {
            addCriterion("SMS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSmsStatusEqualTo(String value) {
            addCriterion("SMS_STATUS =", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusNotEqualTo(String value) {
            addCriterion("SMS_STATUS <>", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusGreaterThan(String value) {
            addCriterion("SMS_STATUS >", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_STATUS >=", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusLessThan(String value) {
            addCriterion("SMS_STATUS <", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusLessThanOrEqualTo(String value) {
            addCriterion("SMS_STATUS <=", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusLike(String value) {
            addCriterion("SMS_STATUS like", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusNotLike(String value) {
            addCriterion("SMS_STATUS not like", value, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusIn(List<String> values) {
            addCriterion("SMS_STATUS in", values, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusNotIn(List<String> values) {
            addCriterion("SMS_STATUS not in", values, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusBetween(String value1, String value2) {
            addCriterion("SMS_STATUS between", value1, value2, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsStatusNotBetween(String value1, String value2) {
            addCriterion("SMS_STATUS not between", value1, value2, "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountIsNull() {
            addCriterion("SMS_RETRY_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountIsNotNull() {
            addCriterion("SMS_RETRY_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountEqualTo(String value) {
            addCriterion("SMS_RETRY_COUNT =", value, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountNotEqualTo(String value) {
            addCriterion("SMS_RETRY_COUNT <>", value, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountGreaterThan(String value) {
            addCriterion("SMS_RETRY_COUNT >", value, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_RETRY_COUNT >=", value, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountLessThan(String value) {
            addCriterion("SMS_RETRY_COUNT <", value, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountLessThanOrEqualTo(String value) {
            addCriterion("SMS_RETRY_COUNT <=", value, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountLike(String value) {
            addCriterion("SMS_RETRY_COUNT like", value, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountNotLike(String value) {
            addCriterion("SMS_RETRY_COUNT not like", value, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountIn(List<String> values) {
            addCriterion("SMS_RETRY_COUNT in", values, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountNotIn(List<String> values) {
            addCriterion("SMS_RETRY_COUNT not in", values, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountBetween(String value1, String value2) {
            addCriterion("SMS_RETRY_COUNT between", value1, value2, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountNotBetween(String value1, String value2) {
            addCriterion("SMS_RETRY_COUNT not between", value1, value2, "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityIsNull() {
            addCriterion("SMS_PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityIsNotNull() {
            addCriterion("SMS_PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityEqualTo(String value) {
            addCriterion("SMS_PRIORITY =", value, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityNotEqualTo(String value) {
            addCriterion("SMS_PRIORITY <>", value, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityGreaterThan(String value) {
            addCriterion("SMS_PRIORITY >", value, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_PRIORITY >=", value, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityLessThan(String value) {
            addCriterion("SMS_PRIORITY <", value, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityLessThanOrEqualTo(String value) {
            addCriterion("SMS_PRIORITY <=", value, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityLike(String value) {
            addCriterion("SMS_PRIORITY like", value, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityNotLike(String value) {
            addCriterion("SMS_PRIORITY not like", value, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityIn(List<String> values) {
            addCriterion("SMS_PRIORITY in", values, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityNotIn(List<String> values) {
            addCriterion("SMS_PRIORITY not in", values, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityBetween(String value1, String value2) {
            addCriterion("SMS_PRIORITY between", value1, value2, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityNotBetween(String value1, String value2) {
            addCriterion("SMS_PRIORITY not between", value1, value2, "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeIsNull() {
            addCriterion("SMS_SEND_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeIsNotNull() {
            addCriterion("SMS_SEND_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeEqualTo(Date value) {
            addCriterion("SMS_SEND_TIME =", value, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeNotEqualTo(Date value) {
            addCriterion("SMS_SEND_TIME <>", value, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeGreaterThan(Date value) {
            addCriterion("SMS_SEND_TIME >", value, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_SEND_TIME >=", value, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeLessThan(Date value) {
            addCriterion("SMS_SEND_TIME <", value, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("SMS_SEND_TIME <=", value, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeIn(List<Date> values) {
            addCriterion("SMS_SEND_TIME in", values, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeNotIn(List<Date> values) {
            addCriterion("SMS_SEND_TIME not in", values, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeBetween(Date value1, Date value2) {
            addCriterion("SMS_SEND_TIME between", value1, value2, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("SMS_SEND_TIME not between", value1, value2, "smsSendTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeIsNull() {
            addCriterion("SMS_BILLING_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeIsNotNull() {
            addCriterion("SMS_BILLING_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeEqualTo(Date value) {
            addCriterion("SMS_BILLING_TIME =", value, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeNotEqualTo(Date value) {
            addCriterion("SMS_BILLING_TIME <>", value, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeGreaterThan(Date value) {
            addCriterion("SMS_BILLING_TIME >", value, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_BILLING_TIME >=", value, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeLessThan(Date value) {
            addCriterion("SMS_BILLING_TIME <", value, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeLessThanOrEqualTo(Date value) {
            addCriterion("SMS_BILLING_TIME <=", value, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeIn(List<Date> values) {
            addCriterion("SMS_BILLING_TIME in", values, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeNotIn(List<Date> values) {
            addCriterion("SMS_BILLING_TIME not in", values, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeBetween(Date value1, Date value2) {
            addCriterion("SMS_BILLING_TIME between", value1, value2, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsBillingTimeNotBetween(Date value1, Date value2) {
            addCriterion("SMS_BILLING_TIME not between", value1, value2, "smsBillingTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeIsNull() {
            addCriterion("SMS_ARCHIVE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeIsNotNull() {
            addCriterion("SMS_ARCHIVE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeEqualTo(Date value) {
            addCriterion("SMS_ARCHIVE_TIME =", value, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeNotEqualTo(Date value) {
            addCriterion("SMS_ARCHIVE_TIME <>", value, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeGreaterThan(Date value) {
            addCriterion("SMS_ARCHIVE_TIME >", value, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_ARCHIVE_TIME >=", value, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeLessThan(Date value) {
            addCriterion("SMS_ARCHIVE_TIME <", value, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("SMS_ARCHIVE_TIME <=", value, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeIn(List<Date> values) {
            addCriterion("SMS_ARCHIVE_TIME in", values, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeNotIn(List<Date> values) {
            addCriterion("SMS_ARCHIVE_TIME not in", values, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeBetween(Date value1, Date value2) {
            addCriterion("SMS_ARCHIVE_TIME between", value1, value2, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsArchiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("SMS_ARCHIVE_TIME not between", value1, value2, "smsArchiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeIsNull() {
            addCriterion("SMS_RESPONSE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeIsNotNull() {
            addCriterion("SMS_RESPONSE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeEqualTo(Date value) {
            addCriterion("SMS_RESPONSE_TIME =", value, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeNotEqualTo(Date value) {
            addCriterion("SMS_RESPONSE_TIME <>", value, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeGreaterThan(Date value) {
            addCriterion("SMS_RESPONSE_TIME >", value, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_RESPONSE_TIME >=", value, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeLessThan(Date value) {
            addCriterion("SMS_RESPONSE_TIME <", value, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeLessThanOrEqualTo(Date value) {
            addCriterion("SMS_RESPONSE_TIME <=", value, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeIn(List<Date> values) {
            addCriterion("SMS_RESPONSE_TIME in", values, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeNotIn(List<Date> values) {
            addCriterion("SMS_RESPONSE_TIME not in", values, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeBetween(Date value1, Date value2) {
            addCriterion("SMS_RESPONSE_TIME between", value1, value2, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseTimeNotBetween(Date value1, Date value2) {
            addCriterion("SMS_RESPONSE_TIME not between", value1, value2, "smsResponseTime");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusIsNull() {
            addCriterion("SMS_RESPONSE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusIsNotNull() {
            addCriterion("SMS_RESPONSE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusEqualTo(String value) {
            addCriterion("SMS_RESPONSE_STATUS =", value, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusNotEqualTo(String value) {
            addCriterion("SMS_RESPONSE_STATUS <>", value, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusGreaterThan(String value) {
            addCriterion("SMS_RESPONSE_STATUS >", value, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_RESPONSE_STATUS >=", value, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusLessThan(String value) {
            addCriterion("SMS_RESPONSE_STATUS <", value, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusLessThanOrEqualTo(String value) {
            addCriterion("SMS_RESPONSE_STATUS <=", value, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusLike(String value) {
            addCriterion("SMS_RESPONSE_STATUS like", value, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusNotLike(String value) {
            addCriterion("SMS_RESPONSE_STATUS not like", value, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusIn(List<String> values) {
            addCriterion("SMS_RESPONSE_STATUS in", values, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusNotIn(List<String> values) {
            addCriterion("SMS_RESPONSE_STATUS not in", values, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusBetween(String value1, String value2) {
            addCriterion("SMS_RESPONSE_STATUS between", value1, value2, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusNotBetween(String value1, String value2) {
            addCriterion("SMS_RESPONSE_STATUS not between", value1, value2, "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdIsNull() {
            addCriterion("SMS_RESPONSE_MSG_ID is null");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdIsNotNull() {
            addCriterion("SMS_RESPONSE_MSG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdEqualTo(String value) {
            addCriterion("SMS_RESPONSE_MSG_ID =", value, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdNotEqualTo(String value) {
            addCriterion("SMS_RESPONSE_MSG_ID <>", value, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdGreaterThan(String value) {
            addCriterion("SMS_RESPONSE_MSG_ID >", value, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_RESPONSE_MSG_ID >=", value, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdLessThan(String value) {
            addCriterion("SMS_RESPONSE_MSG_ID <", value, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdLessThanOrEqualTo(String value) {
            addCriterion("SMS_RESPONSE_MSG_ID <=", value, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdLike(String value) {
            addCriterion("SMS_RESPONSE_MSG_ID like", value, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdNotLike(String value) {
            addCriterion("SMS_RESPONSE_MSG_ID not like", value, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdIn(List<String> values) {
            addCriterion("SMS_RESPONSE_MSG_ID in", values, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdNotIn(List<String> values) {
            addCriterion("SMS_RESPONSE_MSG_ID not in", values, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdBetween(String value1, String value2) {
            addCriterion("SMS_RESPONSE_MSG_ID between", value1, value2, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdNotBetween(String value1, String value2) {
            addCriterion("SMS_RESPONSE_MSG_ID not between", value1, value2, "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitIsNull() {
            addCriterion("SMS_MOBILE_BILLING_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitIsNotNull() {
            addCriterion("SMS_MOBILE_BILLING_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitEqualTo(Integer value) {
            addCriterion("SMS_MOBILE_BILLING_UNIT =", value, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitNotEqualTo(Integer value) {
            addCriterion("SMS_MOBILE_BILLING_UNIT <>", value, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitGreaterThan(Integer value) {
            addCriterion("SMS_MOBILE_BILLING_UNIT >", value, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("SMS_MOBILE_BILLING_UNIT >=", value, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitLessThan(Integer value) {
            addCriterion("SMS_MOBILE_BILLING_UNIT <", value, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitLessThanOrEqualTo(Integer value) {
            addCriterion("SMS_MOBILE_BILLING_UNIT <=", value, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitIn(List<Integer> values) {
            addCriterion("SMS_MOBILE_BILLING_UNIT in", values, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitNotIn(List<Integer> values) {
            addCriterion("SMS_MOBILE_BILLING_UNIT not in", values, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitBetween(Integer value1, Integer value2) {
            addCriterion("SMS_MOBILE_BILLING_UNIT between", value1, value2, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBillingUnitNotBetween(Integer value1, Integer value2) {
            addCriterion("SMS_MOBILE_BILLING_UNIT not between", value1, value2, "smsMobileBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitIsNull() {
            addCriterion("SMS_CONTENT_BILLING_UNIT is null");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitIsNotNull() {
            addCriterion("SMS_CONTENT_BILLING_UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitEqualTo(Integer value) {
            addCriterion("SMS_CONTENT_BILLING_UNIT =", value, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitNotEqualTo(Integer value) {
            addCriterion("SMS_CONTENT_BILLING_UNIT <>", value, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitGreaterThan(Integer value) {
            addCriterion("SMS_CONTENT_BILLING_UNIT >", value, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitGreaterThanOrEqualTo(Integer value) {
            addCriterion("SMS_CONTENT_BILLING_UNIT >=", value, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitLessThan(Integer value) {
            addCriterion("SMS_CONTENT_BILLING_UNIT <", value, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitLessThanOrEqualTo(Integer value) {
            addCriterion("SMS_CONTENT_BILLING_UNIT <=", value, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitIn(List<Integer> values) {
            addCriterion("SMS_CONTENT_BILLING_UNIT in", values, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitNotIn(List<Integer> values) {
            addCriterion("SMS_CONTENT_BILLING_UNIT not in", values, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitBetween(Integer value1, Integer value2) {
            addCriterion("SMS_CONTENT_BILLING_UNIT between", value1, value2, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsContentBillingUnitNotBetween(Integer value1, Integer value2) {
            addCriterion("SMS_CONTENT_BILLING_UNIT not between", value1, value2, "smsContentBillingUnit");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeIsNull() {
            addCriterion("SMS_PLAN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeIsNotNull() {
            addCriterion("SMS_PLAN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeEqualTo(String value) {
            addCriterion("SMS_PLAN_TIME =", value, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeNotEqualTo(String value) {
            addCriterion("SMS_PLAN_TIME <>", value, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeGreaterThan(String value) {
            addCriterion("SMS_PLAN_TIME >", value, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_PLAN_TIME >=", value, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeLessThan(String value) {
            addCriterion("SMS_PLAN_TIME <", value, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeLessThanOrEqualTo(String value) {
            addCriterion("SMS_PLAN_TIME <=", value, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeLike(String value) {
            addCriterion("SMS_PLAN_TIME like", value, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeNotLike(String value) {
            addCriterion("SMS_PLAN_TIME not like", value, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeIn(List<String> values) {
            addCriterion("SMS_PLAN_TIME in", values, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeNotIn(List<String> values) {
            addCriterion("SMS_PLAN_TIME not in", values, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeBetween(String value1, String value2) {
            addCriterion("SMS_PLAN_TIME between", value1, value2, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeNotBetween(String value1, String value2) {
            addCriterion("SMS_PLAN_TIME not between", value1, value2, "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdLikeInsensitive(String value) {
            addCriterion("upper(SMS_MSG_ID) like", value.toUpperCase(), "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMobileListLikeInsensitive(String value) {
            addCriterion("upper(SMS_MOBILE_LIST) like", value.toUpperCase(), "smsMobileList");
            return (Criteria) this;
        }

        public Criteria andSmsContentLikeInsensitive(String value) {
            addCriterion("upper(SMS_CONTENT) like", value.toUpperCase(), "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsSendManLikeInsensitive(String value) {
            addCriterion("upper(SMS_SEND_MAN) like", value.toUpperCase(), "smsSendMan");
            return (Criteria) this;
        }

        public Criteria andSmsStatusLikeInsensitive(String value) {
            addCriterion("upper(SMS_STATUS) like", value.toUpperCase(), "smsStatus");
            return (Criteria) this;
        }

        public Criteria andSmsRetryCountLikeInsensitive(String value) {
            addCriterion("upper(SMS_RETRY_COUNT) like", value.toUpperCase(), "smsRetryCount");
            return (Criteria) this;
        }

        public Criteria andSmsPriorityLikeInsensitive(String value) {
            addCriterion("upper(SMS_PRIORITY) like", value.toUpperCase(), "smsPriority");
            return (Criteria) this;
        }

        public Criteria andSmsResponseStatusLikeInsensitive(String value) {
            addCriterion("upper(SMS_RESPONSE_STATUS) like", value.toUpperCase(), "smsResponseStatus");
            return (Criteria) this;
        }

        public Criteria andSmsResponseMsgIdLikeInsensitive(String value) {
            addCriterion("upper(SMS_RESPONSE_MSG_ID) like", value.toUpperCase(), "smsResponseMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsPlanTimeLikeInsensitive(String value) {
            addCriterion("upper(SMS_PLAN_TIME) like", value.toUpperCase(), "smsPlanTime");
            return (Criteria) this;
        }

        public Criteria andCreateByLikeInsensitive(String value) {
            addCriterion("upper(CREATE_BY) like", value.toUpperCase(), "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLikeInsensitive(String value) {
            addCriterion("upper(UPDATE_BY) like", value.toUpperCase(), "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_archive
     *
     * @mbggenerated do_not_delete_during_merge Fri Sep 26 09:57:55 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_archive
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}