package com.svw.usp.model.standard;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TuSmsChannel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CHANNEL_CODE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CHANNEL_NAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CHANNEL_HOST
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String channelHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CHANNEL_USER_NAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String channelUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CHANNEL_PASSWORD
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String channelPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CHANNEL_SECRET_KEY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String channelSecretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CHANNEL_PRICE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private BigDecimal channelPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CREATE_BY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.CREATE_DATE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.UPDATE_BY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_sms_channel.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CHANNEL_CODE
     *
     * @return the value of tu_sms_channel.CHANNEL_CODE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CHANNEL_CODE
     *
     * @param channelCode the value for tu_sms_channel.CHANNEL_CODE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CHANNEL_NAME
     *
     * @return the value of tu_sms_channel.CHANNEL_NAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CHANNEL_NAME
     *
     * @param channelName the value for tu_sms_channel.CHANNEL_NAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CHANNEL_HOST
     *
     * @return the value of tu_sms_channel.CHANNEL_HOST
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getChannelHost() {
        return channelHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CHANNEL_HOST
     *
     * @param channelHost the value for tu_sms_channel.CHANNEL_HOST
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setChannelHost(String channelHost) {
        this.channelHost = channelHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CHANNEL_USER_NAME
     *
     * @return the value of tu_sms_channel.CHANNEL_USER_NAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getChannelUserName() {
        return channelUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CHANNEL_USER_NAME
     *
     * @param channelUserName the value for tu_sms_channel.CHANNEL_USER_NAME
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setChannelUserName(String channelUserName) {
        this.channelUserName = channelUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CHANNEL_PASSWORD
     *
     * @return the value of tu_sms_channel.CHANNEL_PASSWORD
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getChannelPassword() {
        return channelPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CHANNEL_PASSWORD
     *
     * @param channelPassword the value for tu_sms_channel.CHANNEL_PASSWORD
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setChannelPassword(String channelPassword) {
        this.channelPassword = channelPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CHANNEL_SECRET_KEY
     *
     * @return the value of tu_sms_channel.CHANNEL_SECRET_KEY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getChannelSecretKey() {
        return channelSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CHANNEL_SECRET_KEY
     *
     * @param channelSecretKey the value for tu_sms_channel.CHANNEL_SECRET_KEY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setChannelSecretKey(String channelSecretKey) {
        this.channelSecretKey = channelSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CHANNEL_PRICE
     *
     * @return the value of tu_sms_channel.CHANNEL_PRICE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public BigDecimal getChannelPrice() {
        return channelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CHANNEL_PRICE
     *
     * @param channelPrice the value for tu_sms_channel.CHANNEL_PRICE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setChannelPrice(BigDecimal channelPrice) {
        this.channelPrice = channelPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CREATE_BY
     *
     * @return the value of tu_sms_channel.CREATE_BY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CREATE_BY
     *
     * @param createBy the value for tu_sms_channel.CREATE_BY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.CREATE_DATE
     *
     * @return the value of tu_sms_channel.CREATE_DATE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.CREATE_DATE
     *
     * @param createDate the value for tu_sms_channel.CREATE_DATE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.UPDATE_BY
     *
     * @return the value of tu_sms_channel.UPDATE_BY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.UPDATE_BY
     *
     * @param updateBy the value for tu_sms_channel.UPDATE_BY
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_sms_channel.UPDATE_DATE
     *
     * @return the value of tu_sms_channel.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_sms_channel.UPDATE_DATE
     *
     * @param updateDate the value for tu_sms_channel.UPDATE_DATE
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TuSmsChannel other = (TuSmsChannel) that;
        return (this.getChannelCode() == null ? other.getChannelCode() == null : this.getChannelCode().equals(other.getChannelCode()))
            && (this.getChannelName() == null ? other.getChannelName() == null : this.getChannelName().equals(other.getChannelName()))
            && (this.getChannelHost() == null ? other.getChannelHost() == null : this.getChannelHost().equals(other.getChannelHost()))
            && (this.getChannelUserName() == null ? other.getChannelUserName() == null : this.getChannelUserName().equals(other.getChannelUserName()))
            && (this.getChannelPassword() == null ? other.getChannelPassword() == null : this.getChannelPassword().equals(other.getChannelPassword()))
            && (this.getChannelSecretKey() == null ? other.getChannelSecretKey() == null : this.getChannelSecretKey().equals(other.getChannelSecretKey()))
            && (this.getChannelPrice() == null ? other.getChannelPrice() == null : this.getChannelPrice().equals(other.getChannelPrice()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_channel
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getChannelCode() == null) ? 0 : getChannelCode().hashCode());
        result = prime * result + ((getChannelName() == null) ? 0 : getChannelName().hashCode());
        result = prime * result + ((getChannelHost() == null) ? 0 : getChannelHost().hashCode());
        result = prime * result + ((getChannelUserName() == null) ? 0 : getChannelUserName().hashCode());
        result = prime * result + ((getChannelPassword() == null) ? 0 : getChannelPassword().hashCode());
        result = prime * result + ((getChannelSecretKey() == null) ? 0 : getChannelSecretKey().hashCode());
        result = prime * result + ((getChannelPrice() == null) ? 0 : getChannelPrice().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}