package com.svw.usp.model.standard;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TuSmsReceiveHisCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public TuSmsReceiveHisCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSmsMsgIdIsNull() {
            addCriterion("SMS_MSG_ID is null");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdIsNotNull() {
            addCriterion("SMS_MSG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdEqualTo(String value) {
            addCriterion("SMS_MSG_ID =", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdNotEqualTo(String value) {
            addCriterion("SMS_MSG_ID <>", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdGreaterThan(String value) {
            addCriterion("SMS_MSG_ID >", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_MSG_ID >=", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdLessThan(String value) {
            addCriterion("SMS_MSG_ID <", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdLessThanOrEqualTo(String value) {
            addCriterion("SMS_MSG_ID <=", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdLike(String value) {
            addCriterion("SMS_MSG_ID like", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdNotLike(String value) {
            addCriterion("SMS_MSG_ID not like", value, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdIn(List<String> values) {
            addCriterion("SMS_MSG_ID in", values, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdNotIn(List<String> values) {
            addCriterion("SMS_MSG_ID not in", values, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdBetween(String value1, String value2) {
            addCriterion("SMS_MSG_ID between", value1, value2, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdNotBetween(String value1, String value2) {
            addCriterion("SMS_MSG_ID not between", value1, value2, "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeIsNull() {
            addCriterion("SMS_CHANNEL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeIsNotNull() {
            addCriterion("SMS_CHANNEL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeEqualTo(String value) {
            addCriterion("SMS_CHANNEL_CODE =", value, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeNotEqualTo(String value) {
            addCriterion("SMS_CHANNEL_CODE <>", value, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeGreaterThan(String value) {
            addCriterion("SMS_CHANNEL_CODE >", value, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_CODE >=", value, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeLessThan(String value) {
            addCriterion("SMS_CHANNEL_CODE <", value, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_CODE <=", value, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeLike(String value) {
            addCriterion("SMS_CHANNEL_CODE like", value, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeNotLike(String value) {
            addCriterion("SMS_CHANNEL_CODE not like", value, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeIn(List<String> values) {
            addCriterion("SMS_CHANNEL_CODE in", values, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeNotIn(List<String> values) {
            addCriterion("SMS_CHANNEL_CODE not in", values, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_CODE between", value1, value2, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeNotBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_CODE not between", value1, value2, "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameIsNull() {
            addCriterion("SMS_CHANNEL_USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameIsNotNull() {
            addCriterion("SMS_CHANNEL_USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameEqualTo(String value) {
            addCriterion("SMS_CHANNEL_USERNAME =", value, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameNotEqualTo(String value) {
            addCriterion("SMS_CHANNEL_USERNAME <>", value, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameGreaterThan(String value) {
            addCriterion("SMS_CHANNEL_USERNAME >", value, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_USERNAME >=", value, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameLessThan(String value) {
            addCriterion("SMS_CHANNEL_USERNAME <", value, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameLessThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_USERNAME <=", value, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameLike(String value) {
            addCriterion("SMS_CHANNEL_USERNAME like", value, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameNotLike(String value) {
            addCriterion("SMS_CHANNEL_USERNAME not like", value, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameIn(List<String> values) {
            addCriterion("SMS_CHANNEL_USERNAME in", values, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameNotIn(List<String> values) {
            addCriterion("SMS_CHANNEL_USERNAME not in", values, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_USERNAME between", value1, value2, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameNotBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_USERNAME not between", value1, value2, "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordIsNull() {
            addCriterion("SMS_CHANNEL_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordIsNotNull() {
            addCriterion("SMS_CHANNEL_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordEqualTo(String value) {
            addCriterion("SMS_CHANNEL_PASSWORD =", value, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordNotEqualTo(String value) {
            addCriterion("SMS_CHANNEL_PASSWORD <>", value, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordGreaterThan(String value) {
            addCriterion("SMS_CHANNEL_PASSWORD >", value, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_PASSWORD >=", value, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordLessThan(String value) {
            addCriterion("SMS_CHANNEL_PASSWORD <", value, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordLessThanOrEqualTo(String value) {
            addCriterion("SMS_CHANNEL_PASSWORD <=", value, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordLike(String value) {
            addCriterion("SMS_CHANNEL_PASSWORD like", value, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordNotLike(String value) {
            addCriterion("SMS_CHANNEL_PASSWORD not like", value, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordIn(List<String> values) {
            addCriterion("SMS_CHANNEL_PASSWORD in", values, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordNotIn(List<String> values) {
            addCriterion("SMS_CHANNEL_PASSWORD not in", values, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_PASSWORD between", value1, value2, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordNotBetween(String value1, String value2) {
            addCriterion("SMS_CHANNEL_PASSWORD not between", value1, value2, "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsMobileIsNull() {
            addCriterion("SMS_MOBILE is null");
            return (Criteria) this;
        }

        public Criteria andSmsMobileIsNotNull() {
            addCriterion("SMS_MOBILE is not null");
            return (Criteria) this;
        }

        public Criteria andSmsMobileEqualTo(String value) {
            addCriterion("SMS_MOBILE =", value, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileNotEqualTo(String value) {
            addCriterion("SMS_MOBILE <>", value, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileGreaterThan(String value) {
            addCriterion("SMS_MOBILE >", value, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_MOBILE >=", value, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileLessThan(String value) {
            addCriterion("SMS_MOBILE <", value, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileLessThanOrEqualTo(String value) {
            addCriterion("SMS_MOBILE <=", value, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileLike(String value) {
            addCriterion("SMS_MOBILE like", value, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileNotLike(String value) {
            addCriterion("SMS_MOBILE not like", value, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileIn(List<String> values) {
            addCriterion("SMS_MOBILE in", values, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileNotIn(List<String> values) {
            addCriterion("SMS_MOBILE not in", values, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileBetween(String value1, String value2) {
            addCriterion("SMS_MOBILE between", value1, value2, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsMobileNotBetween(String value1, String value2) {
            addCriterion("SMS_MOBILE not between", value1, value2, "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsContentIsNull() {
            addCriterion("SMS_CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andSmsContentIsNotNull() {
            addCriterion("SMS_CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsContentEqualTo(String value) {
            addCriterion("SMS_CONTENT =", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotEqualTo(String value) {
            addCriterion("SMS_CONTENT <>", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentGreaterThan(String value) {
            addCriterion("SMS_CONTENT >", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_CONTENT >=", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLessThan(String value) {
            addCriterion("SMS_CONTENT <", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLessThanOrEqualTo(String value) {
            addCriterion("SMS_CONTENT <=", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentLike(String value) {
            addCriterion("SMS_CONTENT like", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotLike(String value) {
            addCriterion("SMS_CONTENT not like", value, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentIn(List<String> values) {
            addCriterion("SMS_CONTENT in", values, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotIn(List<String> values) {
            addCriterion("SMS_CONTENT not in", values, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentBetween(String value1, String value2) {
            addCriterion("SMS_CONTENT between", value1, value2, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsContentNotBetween(String value1, String value2) {
            addCriterion("SMS_CONTENT not between", value1, value2, "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysIsNull() {
            addCriterion("SMS_RECEIVE_TIME_YYS is null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysIsNotNull() {
            addCriterion("SMS_RECEIVE_TIME_YYS is not null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME_YYS =", value, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysNotEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME_YYS <>", value, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysGreaterThan(Date value) {
            addCriterion("SMS_RECEIVE_TIME_YYS >", value, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME_YYS >=", value, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysLessThan(Date value) {
            addCriterion("SMS_RECEIVE_TIME_YYS <", value, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysLessThanOrEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME_YYS <=", value, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysIn(List<Date> values) {
            addCriterion("SMS_RECEIVE_TIME_YYS in", values, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysNotIn(List<Date> values) {
            addCriterion("SMS_RECEIVE_TIME_YYS not in", values, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysBetween(Date value1, Date value2) {
            addCriterion("SMS_RECEIVE_TIME_YYS between", value1, value2, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeYysNotBetween(Date value1, Date value2) {
            addCriterion("SMS_RECEIVE_TIME_YYS not between", value1, value2, "smsReceiveTimeYys");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtIsNull() {
            addCriterion("SMS_RECEIVE_TIME_PT is null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtIsNotNull() {
            addCriterion("SMS_RECEIVE_TIME_PT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME_PT =", value, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtNotEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME_PT <>", value, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtGreaterThan(Date value) {
            addCriterion("SMS_RECEIVE_TIME_PT >", value, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME_PT >=", value, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtLessThan(Date value) {
            addCriterion("SMS_RECEIVE_TIME_PT <", value, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtLessThanOrEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME_PT <=", value, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtIn(List<Date> values) {
            addCriterion("SMS_RECEIVE_TIME_PT in", values, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtNotIn(List<Date> values) {
            addCriterion("SMS_RECEIVE_TIME_PT not in", values, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtBetween(Date value1, Date value2) {
            addCriterion("SMS_RECEIVE_TIME_PT between", value1, value2, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimePtNotBetween(Date value1, Date value2) {
            addCriterion("SMS_RECEIVE_TIME_PT not between", value1, value2, "smsReceiveTimePt");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeIsNull() {
            addCriterion("SMS_RECEIVE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeIsNotNull() {
            addCriterion("SMS_RECEIVE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME =", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeNotEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME <>", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeGreaterThan(Date value) {
            addCriterion("SMS_RECEIVE_TIME >", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME >=", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeLessThan(Date value) {
            addCriterion("SMS_RECEIVE_TIME <", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("SMS_RECEIVE_TIME <=", value, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeIn(List<Date> values) {
            addCriterion("SMS_RECEIVE_TIME in", values, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeNotIn(List<Date> values) {
            addCriterion("SMS_RECEIVE_TIME not in", values, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeBetween(Date value1, Date value2) {
            addCriterion("SMS_RECEIVE_TIME between", value1, value2, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("SMS_RECEIVE_TIME not between", value1, value2, "smsReceiveTime");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainIsNull() {
            addCriterion("SMS_RECEIVE_MAIN is null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainIsNotNull() {
            addCriterion("SMS_RECEIVE_MAIN is not null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainEqualTo(String value) {
            addCriterion("SMS_RECEIVE_MAIN =", value, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainNotEqualTo(String value) {
            addCriterion("SMS_RECEIVE_MAIN <>", value, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainGreaterThan(String value) {
            addCriterion("SMS_RECEIVE_MAIN >", value, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_RECEIVE_MAIN >=", value, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainLessThan(String value) {
            addCriterion("SMS_RECEIVE_MAIN <", value, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainLessThanOrEqualTo(String value) {
            addCriterion("SMS_RECEIVE_MAIN <=", value, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainLike(String value) {
            addCriterion("SMS_RECEIVE_MAIN like", value, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainNotLike(String value) {
            addCriterion("SMS_RECEIVE_MAIN not like", value, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainIn(List<String> values) {
            addCriterion("SMS_RECEIVE_MAIN in", values, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainNotIn(List<String> values) {
            addCriterion("SMS_RECEIVE_MAIN not in", values, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainBetween(String value1, String value2) {
            addCriterion("SMS_RECEIVE_MAIN between", value1, value2, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainNotBetween(String value1, String value2) {
            addCriterion("SMS_RECEIVE_MAIN not between", value1, value2, "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdIsNull() {
            addCriterion("SMS_RECEIVE_MSG_ID is null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdIsNotNull() {
            addCriterion("SMS_RECEIVE_MSG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdEqualTo(String value) {
            addCriterion("SMS_RECEIVE_MSG_ID =", value, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdNotEqualTo(String value) {
            addCriterion("SMS_RECEIVE_MSG_ID <>", value, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdGreaterThan(String value) {
            addCriterion("SMS_RECEIVE_MSG_ID >", value, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdGreaterThanOrEqualTo(String value) {
            addCriterion("SMS_RECEIVE_MSG_ID >=", value, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdLessThan(String value) {
            addCriterion("SMS_RECEIVE_MSG_ID <", value, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdLessThanOrEqualTo(String value) {
            addCriterion("SMS_RECEIVE_MSG_ID <=", value, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdLike(String value) {
            addCriterion("SMS_RECEIVE_MSG_ID like", value, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdNotLike(String value) {
            addCriterion("SMS_RECEIVE_MSG_ID not like", value, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdIn(List<String> values) {
            addCriterion("SMS_RECEIVE_MSG_ID in", values, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdNotIn(List<String> values) {
            addCriterion("SMS_RECEIVE_MSG_ID not in", values, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdBetween(String value1, String value2) {
            addCriterion("SMS_RECEIVE_MSG_ID between", value1, value2, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdNotBetween(String value1, String value2) {
            addCriterion("SMS_RECEIVE_MSG_ID not between", value1, value2, "smsReceiveMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsMsgIdLikeInsensitive(String value) {
            addCriterion("upper(SMS_MSG_ID) like", value.toUpperCase(), "smsMsgId");
            return (Criteria) this;
        }

        public Criteria andSmsChannelCodeLikeInsensitive(String value) {
            addCriterion("upper(SMS_CHANNEL_CODE) like", value.toUpperCase(), "smsChannelCode");
            return (Criteria) this;
        }

        public Criteria andSmsChannelUsernameLikeInsensitive(String value) {
            addCriterion("upper(SMS_CHANNEL_USERNAME) like", value.toUpperCase(), "smsChannelUsername");
            return (Criteria) this;
        }

        public Criteria andSmsChannelPasswordLikeInsensitive(String value) {
            addCriterion("upper(SMS_CHANNEL_PASSWORD) like", value.toUpperCase(), "smsChannelPassword");
            return (Criteria) this;
        }

        public Criteria andSmsMobileLikeInsensitive(String value) {
            addCriterion("upper(SMS_MOBILE) like", value.toUpperCase(), "smsMobile");
            return (Criteria) this;
        }

        public Criteria andSmsContentLikeInsensitive(String value) {
            addCriterion("upper(SMS_CONTENT) like", value.toUpperCase(), "smsContent");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMainLikeInsensitive(String value) {
            addCriterion("upper(SMS_RECEIVE_MAIN) like", value.toUpperCase(), "smsReceiveMain");
            return (Criteria) this;
        }

        public Criteria andSmsReceiveMsgIdLikeInsensitive(String value) {
            addCriterion("upper(SMS_RECEIVE_MSG_ID) like", value.toUpperCase(), "smsReceiveMsgId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_sms_receive_his
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}