package com.svw.usp.model.standard;

import java.io.Serializable;
import java.util.Date;

public class TuUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user.USER_NAME
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user.INTERFACE_PASSWORD
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private String interfacePassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user.INTERFACE_SECRET_KEY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private String interfaceSecretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user.LAST_SMS_COUNT
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private Integer lastSmsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user.CREATE_BY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user.CREATE_DATE
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user.UPDATE_BY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user.USER_NAME
     *
     * @return the value of tu_user.USER_NAME
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user.USER_NAME
     *
     * @param userName the value for tu_user.USER_NAME
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user.INTERFACE_PASSWORD
     *
     * @return the value of tu_user.INTERFACE_PASSWORD
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public String getInterfacePassword() {
        return interfacePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user.INTERFACE_PASSWORD
     *
     * @param interfacePassword the value for tu_user.INTERFACE_PASSWORD
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public void setInterfacePassword(String interfacePassword) {
        this.interfacePassword = interfacePassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user.INTERFACE_SECRET_KEY
     *
     * @return the value of tu_user.INTERFACE_SECRET_KEY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public String getInterfaceSecretKey() {
        return interfaceSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user.INTERFACE_SECRET_KEY
     *
     * @param interfaceSecretKey the value for tu_user.INTERFACE_SECRET_KEY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public void setInterfaceSecretKey(String interfaceSecretKey) {
        this.interfaceSecretKey = interfaceSecretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user.LAST_SMS_COUNT
     *
     * @return the value of tu_user.LAST_SMS_COUNT
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public Integer getLastSmsCount() {
        return lastSmsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user.LAST_SMS_COUNT
     *
     * @param lastSmsCount the value for tu_user.LAST_SMS_COUNT
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public void setLastSmsCount(Integer lastSmsCount) {
        this.lastSmsCount = lastSmsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user.CREATE_BY
     *
     * @return the value of tu_user.CREATE_BY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user.CREATE_BY
     *
     * @param createBy the value for tu_user.CREATE_BY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user.CREATE_DATE
     *
     * @return the value of tu_user.CREATE_DATE
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user.CREATE_DATE
     *
     * @param createDate the value for tu_user.CREATE_DATE
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user.UPDATE_BY
     *
     * @return the value of tu_user.UPDATE_BY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user.UPDATE_BY
     *
     * @param updateBy the value for tu_user.UPDATE_BY
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user.UPDATE_DATE
     *
     * @return the value of tu_user.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user.UPDATE_DATE
     *
     * @param updateDate the value for tu_user.UPDATE_DATE
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TuUser other = (TuUser) that;
        return (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getInterfacePassword() == null ? other.getInterfacePassword() == null : this.getInterfacePassword().equals(other.getInterfacePassword()))
            && (this.getInterfaceSecretKey() == null ? other.getInterfaceSecretKey() == null : this.getInterfaceSecretKey().equals(other.getInterfaceSecretKey()))
            && (this.getLastSmsCount() == null ? other.getLastSmsCount() == null : this.getLastSmsCount().equals(other.getLastSmsCount()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Thu Sep 25 17:26:25 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getInterfacePassword() == null) ? 0 : getInterfacePassword().hashCode());
        result = prime * result + ((getInterfaceSecretKey() == null) ? 0 : getInterfaceSecretKey().hashCode());
        result = prime * result + ((getLastSmsCount() == null) ? 0 : getLastSmsCount().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}