package com.svw.usp.model.standard;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TuUserRechargeCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public TuUserRechargeCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRechargeCodeIsNull() {
            addCriterion("RECHARGE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeIsNotNull() {
            addCriterion("RECHARGE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeEqualTo(String value) {
            addCriterion("RECHARGE_CODE =", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeNotEqualTo(String value) {
            addCriterion("RECHARGE_CODE <>", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeGreaterThan(String value) {
            addCriterion("RECHARGE_CODE >", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RECHARGE_CODE >=", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeLessThan(String value) {
            addCriterion("RECHARGE_CODE <", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeLessThanOrEqualTo(String value) {
            addCriterion("RECHARGE_CODE <=", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeLike(String value) {
            addCriterion("RECHARGE_CODE like", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeNotLike(String value) {
            addCriterion("RECHARGE_CODE not like", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeIn(List<String> values) {
            addCriterion("RECHARGE_CODE in", values, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeNotIn(List<String> values) {
            addCriterion("RECHARGE_CODE not in", values, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeBetween(String value1, String value2) {
            addCriterion("RECHARGE_CODE between", value1, value2, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeNotBetween(String value1, String value2) {
            addCriterion("RECHARGE_CODE not between", value1, value2, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeManIsNull() {
            addCriterion("RECHARGE_MAN is null");
            return (Criteria) this;
        }

        public Criteria andRechargeManIsNotNull() {
            addCriterion("RECHARGE_MAN is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeManEqualTo(String value) {
            addCriterion("RECHARGE_MAN =", value, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManNotEqualTo(String value) {
            addCriterion("RECHARGE_MAN <>", value, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManGreaterThan(String value) {
            addCriterion("RECHARGE_MAN >", value, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManGreaterThanOrEqualTo(String value) {
            addCriterion("RECHARGE_MAN >=", value, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManLessThan(String value) {
            addCriterion("RECHARGE_MAN <", value, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManLessThanOrEqualTo(String value) {
            addCriterion("RECHARGE_MAN <=", value, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManLike(String value) {
            addCriterion("RECHARGE_MAN like", value, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManNotLike(String value) {
            addCriterion("RECHARGE_MAN not like", value, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManIn(List<String> values) {
            addCriterion("RECHARGE_MAN in", values, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManNotIn(List<String> values) {
            addCriterion("RECHARGE_MAN not in", values, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManBetween(String value1, String value2) {
            addCriterion("RECHARGE_MAN between", value1, value2, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andRechargeManNotBetween(String value1, String value2) {
            addCriterion("RECHARGE_MAN not between", value1, value2, "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateIsNull() {
            addCriterion("BANK_TRANSFER_CERTIFICATE is null");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateIsNotNull() {
            addCriterion("BANK_TRANSFER_CERTIFICATE is not null");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateEqualTo(String value) {
            addCriterion("BANK_TRANSFER_CERTIFICATE =", value, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateNotEqualTo(String value) {
            addCriterion("BANK_TRANSFER_CERTIFICATE <>", value, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateGreaterThan(String value) {
            addCriterion("BANK_TRANSFER_CERTIFICATE >", value, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_TRANSFER_CERTIFICATE >=", value, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateLessThan(String value) {
            addCriterion("BANK_TRANSFER_CERTIFICATE <", value, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateLessThanOrEqualTo(String value) {
            addCriterion("BANK_TRANSFER_CERTIFICATE <=", value, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateLike(String value) {
            addCriterion("BANK_TRANSFER_CERTIFICATE like", value, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateNotLike(String value) {
            addCriterion("BANK_TRANSFER_CERTIFICATE not like", value, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateIn(List<String> values) {
            addCriterion("BANK_TRANSFER_CERTIFICATE in", values, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateNotIn(List<String> values) {
            addCriterion("BANK_TRANSFER_CERTIFICATE not in", values, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateBetween(String value1, String value2) {
            addCriterion("BANK_TRANSFER_CERTIFICATE between", value1, value2, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateNotBetween(String value1, String value2) {
            addCriterion("BANK_TRANSFER_CERTIFICATE not between", value1, value2, "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateIsNull() {
            addCriterion("BANK_TRANSFER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateIsNotNull() {
            addCriterion("BANK_TRANSFER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateEqualTo(Date value) {
            addCriterion("BANK_TRANSFER_DATE =", value, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateNotEqualTo(Date value) {
            addCriterion("BANK_TRANSFER_DATE <>", value, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateGreaterThan(Date value) {
            addCriterion("BANK_TRANSFER_DATE >", value, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateGreaterThanOrEqualTo(Date value) {
            addCriterion("BANK_TRANSFER_DATE >=", value, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateLessThan(Date value) {
            addCriterion("BANK_TRANSFER_DATE <", value, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateLessThanOrEqualTo(Date value) {
            addCriterion("BANK_TRANSFER_DATE <=", value, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateIn(List<Date> values) {
            addCriterion("BANK_TRANSFER_DATE in", values, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateNotIn(List<Date> values) {
            addCriterion("BANK_TRANSFER_DATE not in", values, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateBetween(Date value1, Date value2) {
            addCriterion("BANK_TRANSFER_DATE between", value1, value2, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andBankTransferDateNotBetween(Date value1, Date value2) {
            addCriterion("BANK_TRANSFER_DATE not between", value1, value2, "bankTransferDate");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusIsNull() {
            addCriterion("RECHARGE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusIsNotNull() {
            addCriterion("RECHARGE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusEqualTo(String value) {
            addCriterion("RECHARGE_STATUS =", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusNotEqualTo(String value) {
            addCriterion("RECHARGE_STATUS <>", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusGreaterThan(String value) {
            addCriterion("RECHARGE_STATUS >", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusGreaterThanOrEqualTo(String value) {
            addCriterion("RECHARGE_STATUS >=", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusLessThan(String value) {
            addCriterion("RECHARGE_STATUS <", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusLessThanOrEqualTo(String value) {
            addCriterion("RECHARGE_STATUS <=", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusLike(String value) {
            addCriterion("RECHARGE_STATUS like", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusNotLike(String value) {
            addCriterion("RECHARGE_STATUS not like", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusIn(List<String> values) {
            addCriterion("RECHARGE_STATUS in", values, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusNotIn(List<String> values) {
            addCriterion("RECHARGE_STATUS not in", values, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusBetween(String value1, String value2) {
            addCriterion("RECHARGE_STATUS between", value1, value2, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusNotBetween(String value1, String value2) {
            addCriterion("RECHARGE_STATUS not between", value1, value2, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManIsNull() {
            addCriterion("RECHARGE_CHECK_MAN is null");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManIsNotNull() {
            addCriterion("RECHARGE_CHECK_MAN is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManEqualTo(String value) {
            addCriterion("RECHARGE_CHECK_MAN =", value, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManNotEqualTo(String value) {
            addCriterion("RECHARGE_CHECK_MAN <>", value, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManGreaterThan(String value) {
            addCriterion("RECHARGE_CHECK_MAN >", value, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManGreaterThanOrEqualTo(String value) {
            addCriterion("RECHARGE_CHECK_MAN >=", value, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManLessThan(String value) {
            addCriterion("RECHARGE_CHECK_MAN <", value, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManLessThanOrEqualTo(String value) {
            addCriterion("RECHARGE_CHECK_MAN <=", value, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManLike(String value) {
            addCriterion("RECHARGE_CHECK_MAN like", value, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManNotLike(String value) {
            addCriterion("RECHARGE_CHECK_MAN not like", value, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManIn(List<String> values) {
            addCriterion("RECHARGE_CHECK_MAN in", values, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManNotIn(List<String> values) {
            addCriterion("RECHARGE_CHECK_MAN not in", values, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManBetween(String value1, String value2) {
            addCriterion("RECHARGE_CHECK_MAN between", value1, value2, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManNotBetween(String value1, String value2) {
            addCriterion("RECHARGE_CHECK_MAN not between", value1, value2, "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeIsNull() {
            addCriterion("RECHARGE_CHECK_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeIsNotNull() {
            addCriterion("RECHARGE_CHECK_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeEqualTo(Date value) {
            addCriterion("RECHARGE_CHECK_TIME =", value, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeNotEqualTo(Date value) {
            addCriterion("RECHARGE_CHECK_TIME <>", value, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeGreaterThan(Date value) {
            addCriterion("RECHARGE_CHECK_TIME >", value, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("RECHARGE_CHECK_TIME >=", value, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeLessThan(Date value) {
            addCriterion("RECHARGE_CHECK_TIME <", value, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeLessThanOrEqualTo(Date value) {
            addCriterion("RECHARGE_CHECK_TIME <=", value, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeIn(List<Date> values) {
            addCriterion("RECHARGE_CHECK_TIME in", values, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeNotIn(List<Date> values) {
            addCriterion("RECHARGE_CHECK_TIME not in", values, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeBetween(Date value1, Date value2) {
            addCriterion("RECHARGE_CHECK_TIME between", value1, value2, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckTimeNotBetween(Date value1, Date value2) {
            addCriterion("RECHARGE_CHECK_TIME not between", value1, value2, "rechargeCheckTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeLikeInsensitive(String value) {
            addCriterion("upper(RECHARGE_CODE) like", value.toUpperCase(), "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeManLikeInsensitive(String value) {
            addCriterion("upper(RECHARGE_MAN) like", value.toUpperCase(), "rechargeMan");
            return (Criteria) this;
        }

        public Criteria andBankTransferCertificateLikeInsensitive(String value) {
            addCriterion("upper(BANK_TRANSFER_CERTIFICATE) like", value.toUpperCase(), "bankTransferCertificate");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusLikeInsensitive(String value) {
            addCriterion("upper(RECHARGE_STATUS) like", value.toUpperCase(), "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeCheckManLikeInsensitive(String value) {
            addCriterion("upper(RECHARGE_CHECK_MAN) like", value.toUpperCase(), "rechargeCheckMan");
            return (Criteria) this;
        }

        public Criteria andCreateByLikeInsensitive(String value) {
            addCriterion("upper(CREATE_BY) like", value.toUpperCase(), "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLikeInsensitive(String value) {
            addCriterion("upper(UPDATE_BY) like", value.toUpperCase(), "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user_recharge
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}