package com.svw.usp.model.standard;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TuUserRecharge implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.RECHARGE_CODE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private String rechargeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.USER_NAME
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.SMS_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private Integer smsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.SMS_TOTAL_PRICE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private BigDecimal smsTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.SMS_UNIT_PRICE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private BigDecimal smsUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private String bankTransferCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private Date bankTransferDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.SMS_BFORE_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private Integer smsBforeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.SMS_AFTER_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private Integer smsAfterCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.SMS_RECHARGE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private Date smsRechargeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.RECHARGE_STATUS
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private String rechargeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.CREATE_BY
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.CREATE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.UPDATE_BY
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.UPDATE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.RECHARGE_CODE
     *
     * @return the value of tu_user_recharge.RECHARGE_CODE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public String getRechargeCode() {
        return rechargeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.RECHARGE_CODE
     *
     * @param rechargeCode the value for tu_user_recharge.RECHARGE_CODE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setRechargeCode(String rechargeCode) {
        this.rechargeCode = rechargeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.USER_NAME
     *
     * @return the value of tu_user_recharge.USER_NAME
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.USER_NAME
     *
     * @param userName the value for tu_user_recharge.USER_NAME
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.SMS_COUNT
     *
     * @return the value of tu_user_recharge.SMS_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Integer getSmsCount() {
        return smsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.SMS_COUNT
     *
     * @param smsCount the value for tu_user_recharge.SMS_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setSmsCount(Integer smsCount) {
        this.smsCount = smsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.SMS_TOTAL_PRICE
     *
     * @return the value of tu_user_recharge.SMS_TOTAL_PRICE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public BigDecimal getSmsTotalPrice() {
        return smsTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.SMS_TOTAL_PRICE
     *
     * @param smsTotalPrice the value for tu_user_recharge.SMS_TOTAL_PRICE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setSmsTotalPrice(BigDecimal smsTotalPrice) {
        this.smsTotalPrice = smsTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.SMS_UNIT_PRICE
     *
     * @return the value of tu_user_recharge.SMS_UNIT_PRICE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public BigDecimal getSmsUnitPrice() {
        return smsUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.SMS_UNIT_PRICE
     *
     * @param smsUnitPrice the value for tu_user_recharge.SMS_UNIT_PRICE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setSmsUnitPrice(BigDecimal smsUnitPrice) {
        this.smsUnitPrice = smsUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @return the value of tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public String getBankTransferCertificate() {
        return bankTransferCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @param bankTransferCertificate the value for tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setBankTransferCertificate(String bankTransferCertificate) {
        this.bankTransferCertificate = bankTransferCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @return the value of tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Date getBankTransferDate() {
        return bankTransferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @param bankTransferDate the value for tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setBankTransferDate(Date bankTransferDate) {
        this.bankTransferDate = bankTransferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.SMS_BFORE_COUNT
     *
     * @return the value of tu_user_recharge.SMS_BFORE_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Integer getSmsBforeCount() {
        return smsBforeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.SMS_BFORE_COUNT
     *
     * @param smsBforeCount the value for tu_user_recharge.SMS_BFORE_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setSmsBforeCount(Integer smsBforeCount) {
        this.smsBforeCount = smsBforeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.SMS_AFTER_COUNT
     *
     * @return the value of tu_user_recharge.SMS_AFTER_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Integer getSmsAfterCount() {
        return smsAfterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.SMS_AFTER_COUNT
     *
     * @param smsAfterCount the value for tu_user_recharge.SMS_AFTER_COUNT
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setSmsAfterCount(Integer smsAfterCount) {
        this.smsAfterCount = smsAfterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.SMS_RECHARGE_DATE
     *
     * @return the value of tu_user_recharge.SMS_RECHARGE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Date getSmsRechargeDate() {
        return smsRechargeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.SMS_RECHARGE_DATE
     *
     * @param smsRechargeDate the value for tu_user_recharge.SMS_RECHARGE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setSmsRechargeDate(Date smsRechargeDate) {
        this.smsRechargeDate = smsRechargeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.RECHARGE_STATUS
     *
     * @return the value of tu_user_recharge.RECHARGE_STATUS
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public String getRechargeStatus() {
        return rechargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.RECHARGE_STATUS
     *
     * @param rechargeStatus the value for tu_user_recharge.RECHARGE_STATUS
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setRechargeStatus(String rechargeStatus) {
        this.rechargeStatus = rechargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.CREATE_BY
     *
     * @return the value of tu_user_recharge.CREATE_BY
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.CREATE_BY
     *
     * @param createBy the value for tu_user_recharge.CREATE_BY
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.CREATE_DATE
     *
     * @return the value of tu_user_recharge.CREATE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.CREATE_DATE
     *
     * @param createDate the value for tu_user_recharge.CREATE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.UPDATE_BY
     *
     * @return the value of tu_user_recharge.UPDATE_BY
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.UPDATE_BY
     *
     * @param updateBy the value for tu_user_recharge.UPDATE_BY
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.UPDATE_DATE
     *
     * @return the value of tu_user_recharge.UPDATE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.UPDATE_DATE
     *
     * @param updateDate the value for tu_user_recharge.UPDATE_DATE
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TuUserRecharge other = (TuUserRecharge) that;
        return (this.getRechargeCode() == null ? other.getRechargeCode() == null : this.getRechargeCode().equals(other.getRechargeCode()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getSmsCount() == null ? other.getSmsCount() == null : this.getSmsCount().equals(other.getSmsCount()))
            && (this.getSmsTotalPrice() == null ? other.getSmsTotalPrice() == null : this.getSmsTotalPrice().equals(other.getSmsTotalPrice()))
            && (this.getSmsUnitPrice() == null ? other.getSmsUnitPrice() == null : this.getSmsUnitPrice().equals(other.getSmsUnitPrice()))
            && (this.getBankTransferCertificate() == null ? other.getBankTransferCertificate() == null : this.getBankTransferCertificate().equals(other.getBankTransferCertificate()))
            && (this.getBankTransferDate() == null ? other.getBankTransferDate() == null : this.getBankTransferDate().equals(other.getBankTransferDate()))
            && (this.getSmsBforeCount() == null ? other.getSmsBforeCount() == null : this.getSmsBforeCount().equals(other.getSmsBforeCount()))
            && (this.getSmsAfterCount() == null ? other.getSmsAfterCount() == null : this.getSmsAfterCount().equals(other.getSmsAfterCount()))
            && (this.getSmsRechargeDate() == null ? other.getSmsRechargeDate() == null : this.getSmsRechargeDate().equals(other.getSmsRechargeDate()))
            && (this.getRechargeStatus() == null ? other.getRechargeStatus() == null : this.getRechargeStatus().equals(other.getRechargeStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRechargeCode() == null) ? 0 : getRechargeCode().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getSmsCount() == null) ? 0 : getSmsCount().hashCode());
        result = prime * result + ((getSmsTotalPrice() == null) ? 0 : getSmsTotalPrice().hashCode());
        result = prime * result + ((getSmsUnitPrice() == null) ? 0 : getSmsUnitPrice().hashCode());
        result = prime * result + ((getBankTransferCertificate() == null) ? 0 : getBankTransferCertificate().hashCode());
        result = prime * result + ((getBankTransferDate() == null) ? 0 : getBankTransferDate().hashCode());
        result = prime * result + ((getSmsBforeCount() == null) ? 0 : getSmsBforeCount().hashCode());
        result = prime * result + ((getSmsAfterCount() == null) ? 0 : getSmsAfterCount().hashCode());
        result = prime * result + ((getSmsRechargeDate() == null) ? 0 : getSmsRechargeDate().hashCode());
        result = prime * result + ((getRechargeStatus() == null) ? 0 : getRechargeStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}