package com.svw.usp.model.standard;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TuUserRechargeItemCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public TuUserRechargeItemCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRechargeCodeIsNull() {
            addCriterion("RECHARGE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeIsNotNull() {
            addCriterion("RECHARGE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeEqualTo(String value) {
            addCriterion("RECHARGE_CODE =", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeNotEqualTo(String value) {
            addCriterion("RECHARGE_CODE <>", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeGreaterThan(String value) {
            addCriterion("RECHARGE_CODE >", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("RECHARGE_CODE >=", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeLessThan(String value) {
            addCriterion("RECHARGE_CODE <", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeLessThanOrEqualTo(String value) {
            addCriterion("RECHARGE_CODE <=", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeLike(String value) {
            addCriterion("RECHARGE_CODE like", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeNotLike(String value) {
            addCriterion("RECHARGE_CODE not like", value, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeIn(List<String> values) {
            addCriterion("RECHARGE_CODE in", values, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeNotIn(List<String> values) {
            addCriterion("RECHARGE_CODE not in", values, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeBetween(String value1, String value2) {
            addCriterion("RECHARGE_CODE between", value1, value2, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeNotBetween(String value1, String value2) {
            addCriterion("RECHARGE_CODE not between", value1, value2, "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andBePrepaidIsNull() {
            addCriterion("BE_PREPAID is null");
            return (Criteria) this;
        }

        public Criteria andBePrepaidIsNotNull() {
            addCriterion("BE_PREPAID is not null");
            return (Criteria) this;
        }

        public Criteria andBePrepaidEqualTo(String value) {
            addCriterion("BE_PREPAID =", value, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidNotEqualTo(String value) {
            addCriterion("BE_PREPAID <>", value, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidGreaterThan(String value) {
            addCriterion("BE_PREPAID >", value, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidGreaterThanOrEqualTo(String value) {
            addCriterion("BE_PREPAID >=", value, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidLessThan(String value) {
            addCriterion("BE_PREPAID <", value, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidLessThanOrEqualTo(String value) {
            addCriterion("BE_PREPAID <=", value, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidLike(String value) {
            addCriterion("BE_PREPAID like", value, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidNotLike(String value) {
            addCriterion("BE_PREPAID not like", value, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidIn(List<String> values) {
            addCriterion("BE_PREPAID in", values, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidNotIn(List<String> values) {
            addCriterion("BE_PREPAID not in", values, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidBetween(String value1, String value2) {
            addCriterion("BE_PREPAID between", value1, value2, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andBePrepaidNotBetween(String value1, String value2) {
            addCriterion("BE_PREPAID not between", value1, value2, "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceIsNull() {
            addCriterion("SMS_TOTAL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceIsNotNull() {
            addCriterion("SMS_TOTAL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceEqualTo(BigDecimal value) {
            addCriterion("SMS_TOTAL_PRICE =", value, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceNotEqualTo(BigDecimal value) {
            addCriterion("SMS_TOTAL_PRICE <>", value, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceGreaterThan(BigDecimal value) {
            addCriterion("SMS_TOTAL_PRICE >", value, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SMS_TOTAL_PRICE >=", value, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceLessThan(BigDecimal value) {
            addCriterion("SMS_TOTAL_PRICE <", value, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SMS_TOTAL_PRICE <=", value, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceIn(List<BigDecimal> values) {
            addCriterion("SMS_TOTAL_PRICE in", values, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceNotIn(List<BigDecimal> values) {
            addCriterion("SMS_TOTAL_PRICE not in", values, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SMS_TOTAL_PRICE between", value1, value2, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SMS_TOTAL_PRICE not between", value1, value2, "smsTotalPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceIsNull() {
            addCriterion("SMS_UNIT_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceIsNotNull() {
            addCriterion("SMS_UNIT_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceEqualTo(BigDecimal value) {
            addCriterion("SMS_UNIT_PRICE =", value, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceNotEqualTo(BigDecimal value) {
            addCriterion("SMS_UNIT_PRICE <>", value, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceGreaterThan(BigDecimal value) {
            addCriterion("SMS_UNIT_PRICE >", value, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SMS_UNIT_PRICE >=", value, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceLessThan(BigDecimal value) {
            addCriterion("SMS_UNIT_PRICE <", value, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SMS_UNIT_PRICE <=", value, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceIn(List<BigDecimal> values) {
            addCriterion("SMS_UNIT_PRICE in", values, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceNotIn(List<BigDecimal> values) {
            addCriterion("SMS_UNIT_PRICE not in", values, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SMS_UNIT_PRICE between", value1, value2, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsUnitPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SMS_UNIT_PRICE not between", value1, value2, "smsUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountIsNull() {
            addCriterion("SMS_PLAN_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountIsNotNull() {
            addCriterion("SMS_PLAN_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountEqualTo(Integer value) {
            addCriterion("SMS_PLAN_COUNT =", value, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountNotEqualTo(Integer value) {
            addCriterion("SMS_PLAN_COUNT <>", value, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountGreaterThan(Integer value) {
            addCriterion("SMS_PLAN_COUNT >", value, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("SMS_PLAN_COUNT >=", value, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountLessThan(Integer value) {
            addCriterion("SMS_PLAN_COUNT <", value, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountLessThanOrEqualTo(Integer value) {
            addCriterion("SMS_PLAN_COUNT <=", value, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountIn(List<Integer> values) {
            addCriterion("SMS_PLAN_COUNT in", values, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountNotIn(List<Integer> values) {
            addCriterion("SMS_PLAN_COUNT not in", values, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountBetween(Integer value1, Integer value2) {
            addCriterion("SMS_PLAN_COUNT between", value1, value2, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsPlanCountNotBetween(Integer value1, Integer value2) {
            addCriterion("SMS_PLAN_COUNT not between", value1, value2, "smsPlanCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountIsNull() {
            addCriterion("SMS_REAL_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountIsNotNull() {
            addCriterion("SMS_REAL_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountEqualTo(Integer value) {
            addCriterion("SMS_REAL_COUNT =", value, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountNotEqualTo(Integer value) {
            addCriterion("SMS_REAL_COUNT <>", value, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountGreaterThan(Integer value) {
            addCriterion("SMS_REAL_COUNT >", value, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("SMS_REAL_COUNT >=", value, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountLessThan(Integer value) {
            addCriterion("SMS_REAL_COUNT <", value, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountLessThanOrEqualTo(Integer value) {
            addCriterion("SMS_REAL_COUNT <=", value, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountIn(List<Integer> values) {
            addCriterion("SMS_REAL_COUNT in", values, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountNotIn(List<Integer> values) {
            addCriterion("SMS_REAL_COUNT not in", values, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountBetween(Integer value1, Integer value2) {
            addCriterion("SMS_REAL_COUNT between", value1, value2, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsRealCountNotBetween(Integer value1, Integer value2) {
            addCriterion("SMS_REAL_COUNT not between", value1, value2, "smsRealCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountIsNull() {
            addCriterion("SMS_BFORE_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountIsNotNull() {
            addCriterion("SMS_BFORE_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountEqualTo(Integer value) {
            addCriterion("SMS_BFORE_COUNT =", value, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountNotEqualTo(Integer value) {
            addCriterion("SMS_BFORE_COUNT <>", value, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountGreaterThan(Integer value) {
            addCriterion("SMS_BFORE_COUNT >", value, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("SMS_BFORE_COUNT >=", value, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountLessThan(Integer value) {
            addCriterion("SMS_BFORE_COUNT <", value, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountLessThanOrEqualTo(Integer value) {
            addCriterion("SMS_BFORE_COUNT <=", value, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountIn(List<Integer> values) {
            addCriterion("SMS_BFORE_COUNT in", values, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountNotIn(List<Integer> values) {
            addCriterion("SMS_BFORE_COUNT not in", values, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountBetween(Integer value1, Integer value2) {
            addCriterion("SMS_BFORE_COUNT between", value1, value2, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsBforeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("SMS_BFORE_COUNT not between", value1, value2, "smsBforeCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountIsNull() {
            addCriterion("SMS_AFTER_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountIsNotNull() {
            addCriterion("SMS_AFTER_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountEqualTo(Integer value) {
            addCriterion("SMS_AFTER_COUNT =", value, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountNotEqualTo(Integer value) {
            addCriterion("SMS_AFTER_COUNT <>", value, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountGreaterThan(Integer value) {
            addCriterion("SMS_AFTER_COUNT >", value, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("SMS_AFTER_COUNT >=", value, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountLessThan(Integer value) {
            addCriterion("SMS_AFTER_COUNT <", value, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountLessThanOrEqualTo(Integer value) {
            addCriterion("SMS_AFTER_COUNT <=", value, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountIn(List<Integer> values) {
            addCriterion("SMS_AFTER_COUNT in", values, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountNotIn(List<Integer> values) {
            addCriterion("SMS_AFTER_COUNT not in", values, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountBetween(Integer value1, Integer value2) {
            addCriterion("SMS_AFTER_COUNT between", value1, value2, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsAfterCountNotBetween(Integer value1, Integer value2) {
            addCriterion("SMS_AFTER_COUNT not between", value1, value2, "smsAfterCount");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateIsNull() {
            addCriterion("SMS_RECHARGE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateIsNotNull() {
            addCriterion("SMS_RECHARGE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateEqualTo(Date value) {
            addCriterion("SMS_RECHARGE_DATE =", value, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateNotEqualTo(Date value) {
            addCriterion("SMS_RECHARGE_DATE <>", value, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateGreaterThan(Date value) {
            addCriterion("SMS_RECHARGE_DATE >", value, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SMS_RECHARGE_DATE >=", value, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateLessThan(Date value) {
            addCriterion("SMS_RECHARGE_DATE <", value, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateLessThanOrEqualTo(Date value) {
            addCriterion("SMS_RECHARGE_DATE <=", value, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateIn(List<Date> values) {
            addCriterion("SMS_RECHARGE_DATE in", values, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateNotIn(List<Date> values) {
            addCriterion("SMS_RECHARGE_DATE not in", values, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateBetween(Date value1, Date value2) {
            addCriterion("SMS_RECHARGE_DATE between", value1, value2, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andSmsRechargeDateNotBetween(Date value1, Date value2) {
            addCriterion("SMS_RECHARGE_DATE not between", value1, value2, "smsRechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusIsNull() {
            addCriterion("RECHARGE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusIsNotNull() {
            addCriterion("RECHARGE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusEqualTo(String value) {
            addCriterion("RECHARGE_STATUS =", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusNotEqualTo(String value) {
            addCriterion("RECHARGE_STATUS <>", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusGreaterThan(String value) {
            addCriterion("RECHARGE_STATUS >", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusGreaterThanOrEqualTo(String value) {
            addCriterion("RECHARGE_STATUS >=", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusLessThan(String value) {
            addCriterion("RECHARGE_STATUS <", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusLessThanOrEqualTo(String value) {
            addCriterion("RECHARGE_STATUS <=", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusLike(String value) {
            addCriterion("RECHARGE_STATUS like", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusNotLike(String value) {
            addCriterion("RECHARGE_STATUS not like", value, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusIn(List<String> values) {
            addCriterion("RECHARGE_STATUS in", values, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusNotIn(List<String> values) {
            addCriterion("RECHARGE_STATUS not in", values, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusBetween(String value1, String value2) {
            addCriterion("RECHARGE_STATUS between", value1, value2, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusNotBetween(String value1, String value2) {
            addCriterion("RECHARGE_STATUS not between", value1, value2, "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andRechargeCodeLikeInsensitive(String value) {
            addCriterion("upper(RECHARGE_CODE) like", value.toUpperCase(), "rechargeCode");
            return (Criteria) this;
        }

        public Criteria andBePrepaidLikeInsensitive(String value) {
            addCriterion("upper(BE_PREPAID) like", value.toUpperCase(), "bePrepaid");
            return (Criteria) this;
        }

        public Criteria andRechargeStatusLikeInsensitive(String value) {
            addCriterion("upper(RECHARGE_STATUS) like", value.toUpperCase(), "rechargeStatus");
            return (Criteria) this;
        }

        public Criteria andCreateByLikeInsensitive(String value) {
            addCriterion("upper(CREATE_BY) like", value.toUpperCase(), "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLikeInsensitive(String value) {
            addCriterion("upper(UPDATE_BY) like", value.toUpperCase(), "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}