package com.svw.usp.model.standard;

import java.io.Serializable;
import java.util.Date;

public class TuUserRecharge implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.RECHARGE_CODE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private String rechargeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.RECHARGE_MAN
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private String rechargeMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private String bankTransferCertificate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private Date bankTransferDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.RECHARGE_STATUS
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private String rechargeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.RECHARGE_CHECK_MAN
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private String rechargeCheckMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.RECHARGE_CHECK_TIME
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private Date rechargeCheckTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.CREATE_BY
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.CREATE_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.UPDATE_BY
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tu_user_recharge.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.RECHARGE_CODE
     *
     * @return the value of tu_user_recharge.RECHARGE_CODE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public String getRechargeCode() {
        return rechargeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.RECHARGE_CODE
     *
     * @param rechargeCode the value for tu_user_recharge.RECHARGE_CODE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setRechargeCode(String rechargeCode) {
        this.rechargeCode = rechargeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.RECHARGE_MAN
     *
     * @return the value of tu_user_recharge.RECHARGE_MAN
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public String getRechargeMan() {
        return rechargeMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.RECHARGE_MAN
     *
     * @param rechargeMan the value for tu_user_recharge.RECHARGE_MAN
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setRechargeMan(String rechargeMan) {
        this.rechargeMan = rechargeMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @return the value of tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public String getBankTransferCertificate() {
        return bankTransferCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @param bankTransferCertificate the value for tu_user_recharge.BANK_TRANSFER_CERTIFICATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setBankTransferCertificate(String bankTransferCertificate) {
        this.bankTransferCertificate = bankTransferCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @return the value of tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public Date getBankTransferDate() {
        return bankTransferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @param bankTransferDate the value for tu_user_recharge.BANK_TRANSFER_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setBankTransferDate(Date bankTransferDate) {
        this.bankTransferDate = bankTransferDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.RECHARGE_STATUS
     *
     * @return the value of tu_user_recharge.RECHARGE_STATUS
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public String getRechargeStatus() {
        return rechargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.RECHARGE_STATUS
     *
     * @param rechargeStatus the value for tu_user_recharge.RECHARGE_STATUS
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setRechargeStatus(String rechargeStatus) {
        this.rechargeStatus = rechargeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.RECHARGE_CHECK_MAN
     *
     * @return the value of tu_user_recharge.RECHARGE_CHECK_MAN
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public String getRechargeCheckMan() {
        return rechargeCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.RECHARGE_CHECK_MAN
     *
     * @param rechargeCheckMan the value for tu_user_recharge.RECHARGE_CHECK_MAN
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setRechargeCheckMan(String rechargeCheckMan) {
        this.rechargeCheckMan = rechargeCheckMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.RECHARGE_CHECK_TIME
     *
     * @return the value of tu_user_recharge.RECHARGE_CHECK_TIME
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public Date getRechargeCheckTime() {
        return rechargeCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.RECHARGE_CHECK_TIME
     *
     * @param rechargeCheckTime the value for tu_user_recharge.RECHARGE_CHECK_TIME
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setRechargeCheckTime(Date rechargeCheckTime) {
        this.rechargeCheckTime = rechargeCheckTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.CREATE_BY
     *
     * @return the value of tu_user_recharge.CREATE_BY
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.CREATE_BY
     *
     * @param createBy the value for tu_user_recharge.CREATE_BY
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.CREATE_DATE
     *
     * @return the value of tu_user_recharge.CREATE_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.CREATE_DATE
     *
     * @param createDate the value for tu_user_recharge.CREATE_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.UPDATE_BY
     *
     * @return the value of tu_user_recharge.UPDATE_BY
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.UPDATE_BY
     *
     * @param updateBy the value for tu_user_recharge.UPDATE_BY
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tu_user_recharge.UPDATE_DATE
     *
     * @return the value of tu_user_recharge.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tu_user_recharge.UPDATE_DATE
     *
     * @param updateDate the value for tu_user_recharge.UPDATE_DATE
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TuUserRecharge other = (TuUserRecharge) that;
        return (this.getRechargeCode() == null ? other.getRechargeCode() == null : this.getRechargeCode().equals(other.getRechargeCode()))
            && (this.getRechargeMan() == null ? other.getRechargeMan() == null : this.getRechargeMan().equals(other.getRechargeMan()))
            && (this.getBankTransferCertificate() == null ? other.getBankTransferCertificate() == null : this.getBankTransferCertificate().equals(other.getBankTransferCertificate()))
            && (this.getBankTransferDate() == null ? other.getBankTransferDate() == null : this.getBankTransferDate().equals(other.getBankTransferDate()))
            && (this.getRechargeStatus() == null ? other.getRechargeStatus() == null : this.getRechargeStatus().equals(other.getRechargeStatus()))
            && (this.getRechargeCheckMan() == null ? other.getRechargeCheckMan() == null : this.getRechargeCheckMan().equals(other.getRechargeCheckMan()))
            && (this.getRechargeCheckTime() == null ? other.getRechargeCheckTime() == null : this.getRechargeCheckTime().equals(other.getRechargeCheckTime()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRechargeCode() == null) ? 0 : getRechargeCode().hashCode());
        result = prime * result + ((getRechargeMan() == null) ? 0 : getRechargeMan().hashCode());
        result = prime * result + ((getBankTransferCertificate() == null) ? 0 : getBankTransferCertificate().hashCode());
        result = prime * result + ((getBankTransferDate() == null) ? 0 : getBankTransferDate().hashCode());
        result = prime * result + ((getRechargeStatus() == null) ? 0 : getRechargeStatus().hashCode());
        result = prime * result + ((getRechargeCheckMan() == null) ? 0 : getRechargeCheckMan().hashCode());
        result = prime * result + ((getRechargeCheckTime() == null) ? 0 : getRechargeCheckTime().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}