package com.svw.usp.model.standard;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TuUserCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public TuUserCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNull() {
            addCriterion("CHANNEL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNotNull() {
            addCriterion("CHANNEL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeEqualTo(String value) {
            addCriterion("CHANNEL_CODE =", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotEqualTo(String value) {
            addCriterion("CHANNEL_CODE <>", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThan(String value) {
            addCriterion("CHANNEL_CODE >", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CHANNEL_CODE >=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThan(String value) {
            addCriterion("CHANNEL_CODE <", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("CHANNEL_CODE <=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLike(String value) {
            addCriterion("CHANNEL_CODE like", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotLike(String value) {
            addCriterion("CHANNEL_CODE not like", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIn(List<String> values) {
            addCriterion("CHANNEL_CODE in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotIn(List<String> values) {
            addCriterion("CHANNEL_CODE not in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeBetween(String value1, String value2) {
            addCriterion("CHANNEL_CODE between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotBetween(String value1, String value2) {
            addCriterion("CHANNEL_CODE not between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordIsNull() {
            addCriterion("INTERFACE_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordIsNotNull() {
            addCriterion("INTERFACE_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordEqualTo(String value) {
            addCriterion("INTERFACE_PASSWORD =", value, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordNotEqualTo(String value) {
            addCriterion("INTERFACE_PASSWORD <>", value, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordGreaterThan(String value) {
            addCriterion("INTERFACE_PASSWORD >", value, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordGreaterThanOrEqualTo(String value) {
            addCriterion("INTERFACE_PASSWORD >=", value, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordLessThan(String value) {
            addCriterion("INTERFACE_PASSWORD <", value, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordLessThanOrEqualTo(String value) {
            addCriterion("INTERFACE_PASSWORD <=", value, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordLike(String value) {
            addCriterion("INTERFACE_PASSWORD like", value, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordNotLike(String value) {
            addCriterion("INTERFACE_PASSWORD not like", value, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordIn(List<String> values) {
            addCriterion("INTERFACE_PASSWORD in", values, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordNotIn(List<String> values) {
            addCriterion("INTERFACE_PASSWORD not in", values, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordBetween(String value1, String value2) {
            addCriterion("INTERFACE_PASSWORD between", value1, value2, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordNotBetween(String value1, String value2) {
            addCriterion("INTERFACE_PASSWORD not between", value1, value2, "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyIsNull() {
            addCriterion("INTERFACE_SECRET_KEY is null");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyIsNotNull() {
            addCriterion("INTERFACE_SECRET_KEY is not null");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyEqualTo(String value) {
            addCriterion("INTERFACE_SECRET_KEY =", value, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyNotEqualTo(String value) {
            addCriterion("INTERFACE_SECRET_KEY <>", value, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyGreaterThan(String value) {
            addCriterion("INTERFACE_SECRET_KEY >", value, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyGreaterThanOrEqualTo(String value) {
            addCriterion("INTERFACE_SECRET_KEY >=", value, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyLessThan(String value) {
            addCriterion("INTERFACE_SECRET_KEY <", value, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyLessThanOrEqualTo(String value) {
            addCriterion("INTERFACE_SECRET_KEY <=", value, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyLike(String value) {
            addCriterion("INTERFACE_SECRET_KEY like", value, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyNotLike(String value) {
            addCriterion("INTERFACE_SECRET_KEY not like", value, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyIn(List<String> values) {
            addCriterion("INTERFACE_SECRET_KEY in", values, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyNotIn(List<String> values) {
            addCriterion("INTERFACE_SECRET_KEY not in", values, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyBetween(String value1, String value2) {
            addCriterion("INTERFACE_SECRET_KEY between", value1, value2, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyNotBetween(String value1, String value2) {
            addCriterion("INTERFACE_SECRET_KEY not between", value1, value2, "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountIsNull() {
            addCriterion("LAST_SMS_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountIsNotNull() {
            addCriterion("LAST_SMS_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountEqualTo(Integer value) {
            addCriterion("LAST_SMS_COUNT =", value, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountNotEqualTo(Integer value) {
            addCriterion("LAST_SMS_COUNT <>", value, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountGreaterThan(Integer value) {
            addCriterion("LAST_SMS_COUNT >", value, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("LAST_SMS_COUNT >=", value, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountLessThan(Integer value) {
            addCriterion("LAST_SMS_COUNT <", value, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountLessThanOrEqualTo(Integer value) {
            addCriterion("LAST_SMS_COUNT <=", value, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountIn(List<Integer> values) {
            addCriterion("LAST_SMS_COUNT in", values, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountNotIn(List<Integer> values) {
            addCriterion("LAST_SMS_COUNT not in", values, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountBetween(Integer value1, Integer value2) {
            addCriterion("LAST_SMS_COUNT between", value1, value2, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andLastSmsCountNotBetween(Integer value1, Integer value2) {
            addCriterion("LAST_SMS_COUNT not between", value1, value2, "lastSmsCount");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("CREATE_BY like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("CREATE_BY not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("UPDATE_BY like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("UPDATE_BY not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUserNameLikeInsensitive(String value) {
            addCriterion("upper(USER_NAME) like", value.toUpperCase(), "userName");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLikeInsensitive(String value) {
            addCriterion("upper(CHANNEL_CODE) like", value.toUpperCase(), "channelCode");
            return (Criteria) this;
        }

        public Criteria andInterfacePasswordLikeInsensitive(String value) {
            addCriterion("upper(INTERFACE_PASSWORD) like", value.toUpperCase(), "interfacePassword");
            return (Criteria) this;
        }

        public Criteria andInterfaceSecretKeyLikeInsensitive(String value) {
            addCriterion("upper(INTERFACE_SECRET_KEY) like", value.toUpperCase(), "interfaceSecretKey");
            return (Criteria) this;
        }

        public Criteria andCreateByLikeInsensitive(String value) {
            addCriterion("upper(CREATE_BY) like", value.toUpperCase(), "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLikeInsensitive(String value) {
            addCriterion("upper(UPDATE_BY) like", value.toUpperCase(), "updateBy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tu_user
     *
     * @mbggenerated Wed Nov 19 13:45:24 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}