package com.svw.usp.mapper.standard;

import com.svw.usp.model.standard.TsTestTable;
import com.svw.usp.model.standard.TsTestTableCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TsTestTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int countByExample(TsTestTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int deleteByExample(TsTestTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int deleteByPrimaryKey(String jobCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int insert(TsTestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int insertSelective(TsTestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    List<TsTestTable> selectByExample(TsTestTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    TsTestTable selectByPrimaryKey(String jobCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int updateByExampleSelective(@Param("record") TsTestTable record, @Param("example") TsTestTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int updateByExample(@Param("record") TsTestTable record, @Param("example") TsTestTableCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int updateByPrimaryKeySelective(TsTestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TS_TEST_TABLE
     *
     * @mbggenerated Tue Aug 12 10:49:38 CST 2014
     */
    int updateByPrimaryKey(TsTestTable record);
}