package com.svw.usp.mapper.standard;

import com.svw.usp.model.standard.TuCostsLadderCriteria;
import com.svw.usp.model.standard.TuCostsLadderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TuCostsLadderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int countByExample(TuCostsLadderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int deleteByExample(TuCostsLadderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int deleteByPrimaryKey(TuCostsLadderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int insert(TuCostsLadderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int insertSelective(TuCostsLadderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    List<TuCostsLadderKey> selectByExample(TuCostsLadderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") TuCostsLadderKey record, @Param("example") TuCostsLadderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_costs_ladder
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int updateByExample(@Param("record") TuCostsLadderKey record, @Param("example") TuCostsLadderCriteria example);
}