package com.svw.usp.mapper.standard;

import com.svw.usp.model.standard.TuUserRecharge;
import com.svw.usp.model.standard.TuUserRechargeCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TuUserRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int countByExample(TuUserRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int deleteByExample(TuUserRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int deleteByPrimaryKey(String rechargeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int insert(TuUserRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int insertSelective(TuUserRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    List<TuUserRecharge> selectByExample(TuUserRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    TuUserRecharge selectByPrimaryKey(String rechargeCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") TuUserRecharge record, @Param("example") TuUserRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int updateByExample(@Param("record") TuUserRecharge record, @Param("example") TuUserRechargeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int updateByPrimaryKeySelective(TuUserRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge
     *
     * @mbggenerated Fri Sep 26 09:57:55 CST 2014
     */
    int updateByPrimaryKey(TuUserRecharge record);
}