package com.svw.usp.mapper.standard;

import com.svw.usp.model.standard.TuUserRechargeItem;
import com.svw.usp.model.standard.TuUserRechargeItemCriteria;
import com.svw.usp.model.standard.TuUserRechargeItemKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TuUserRechargeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int countByExample(TuUserRechargeItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int deleteByExample(TuUserRechargeItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int deleteByPrimaryKey(TuUserRechargeItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int insert(TuUserRechargeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int insertSelective(TuUserRechargeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    List<TuUserRechargeItem> selectByExample(TuUserRechargeItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    TuUserRechargeItem selectByPrimaryKey(TuUserRechargeItemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int updateByExampleSelective(@Param("record") TuUserRechargeItem record, @Param("example") TuUserRechargeItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int updateByExample(@Param("record") TuUserRechargeItem record, @Param("example") TuUserRechargeItemCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int updateByPrimaryKeySelective(TuUserRechargeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tu_user_recharge_item
     *
     * @mbggenerated Wed Oct 08 17:51:00 CST 2014
     */
    int updateByPrimaryKey(TuUserRechargeItem record);
}